### ISSUE TITLE
Ability to ignore certain files or folders

### ISSUE THREAD

**Issue by chrisdarroch** [facebook/jscodeshift#106]
If I point `jscodeshift` at the root directory of my project, and I have compiled assets in my project, `jscodeshift` will attempt to parse and transform all files and subfolders in the directory. 

Having the ability to ignore certain files and folders would be a boon; it'd mean being able to run transforms on a repo without needing a separate pristine copy, or first having to run `git clean -dfx` to remove generated files.

**Comment by chrisdarroch** [comment]
Perhaps being able to do something like `jscodeshift -t <transform> --ignore ~/.gitignore ~/path/to/repo` would be suitable?

**Comment by fkling** [comment]
Duplicate of #53 ?

**Comment by chrisdarroch** [comment]
Seems to be a dupe, yes.
