### ISSUE TITLE
[Traversals] Add `closestScope`

### ISSUE THREAD

**Issue by cpojer** [facebook/jscodeshift#12]
A `closestScope` function would return the closest scope (walking up the parent nodes) which is either a function, arrow function, method declaration, function declaration or function expression (and maybe others).

This is something that has come up repeatedly for me when trying to trace identifiers or other things around in an AST.

Example of where I did the traversal manually: https://github.com/cpojer/js-codemod/commit/a20a5e15aa4c2a268b4ff9982aeb5459716da7e8

**Comment by fkling** [comment]
I guess this can be closed because we already have [`closestScope`](/facebook/jscodeshift/blob/master/src/collections/Node.js#L65)?

**Comment by cpojer** [comment]
wish I had known about this -.-

**Comment by fkling** [comment]
https://github.com/facebook/jscodeshift/search?utf8=%E2%9C%93&q=scope ;)
