### ISSUE TITLE
Stats don’t appear in console output

### ISSUE THREAD

**Issue by gaearon** [facebook/jscodeshift#123]
<img width="489" alt="screen shot 2016-06-22 at 21 04 33" src="https://cloud.githubusercontent.com/assets/810438/16281806/dce0325a-38bd-11e6-9b6d-0ba87e825b6c.png">

My first guess would be that [process.stdout.write](https://github.com/facebook/jscodeshift/blob/1e077694913e4aa84cb97bebc08cdb72a8e77c34/src/Runner.js#L68) doesn’t actually accept multiple arguments so only name gets logged.

**Comment by fkling** [comment]
Is that still an issue after f287e2d9af4544ad78b0b1397be6540957b9d4e4 ?

**Comment by gaearon** [comment]
Will check tomorrow!

**Comment by DrewML** [comment]
Was broken for me as well - just updated and things are working. Thanks @fkling!
