### ISSUE TITLE
Does jscodeshift work with css/scss/etc..?

### ISSUE THREAD

**Issue by tnrich** [facebook/jscodeshift#124]
Hey there,

First off, thanks for the awesome looking tool. I thought I'd write a simple codemod to change px to em's and wanted to use jscodeshift to do it. 

Here's the transform I'm using: http://astexplorer.net/#/usDeoLTPFE/2

And here's the jscodeshift command I was running: 

`jscodeshift . -t ./codemods/scss-px-to-em.js -v 1 --extensions scss `

I must be doing something wrong because the output is totally wrong. So, is it possible to use jscodeshift to do postcss transforms? 

Thanks very much!

**Comment by DrewML** [comment]
Hey Thomas,

Not a maintainer, but my guess is that this isn't something `jscodeshift` could do. `jscodeshift` uses [recast](https://github.com/benjamn/recast) under the hood for parsing and printing, which is designed specifically for JavaScript ASTs.

You might be able to use the `postcss-cli` for that job. It looks like there is [a configuration option that let's you replace source files with the transformed output](https://www.npmjs.com/package/postcss-cli#--replace-r)

**Comment by benjamn** [comment]
The techniques that `recast` uses are generic enough to work for any language that has an AST, though you'd have to implement [pretty-printer cases](https://github.com/benjamn/recast/blob/0d4a15ce8e680fe052d96a6b8aa5baa493348958/lib/printer.js#L223) for all those AST types.

That said, I think CSS formatting tends to be much more regular than JS formatting, so you could more easily get away with just parsing, transforming, and pretty-printing your CSS, without so much effort to preserve idiomatic formatting.

**Comment by fkling** [comment]
As said, jscodeshift currently only really works for JavaScript, but there are no technical limitations why it couldn't work for other languages in the future (I actually want that).

As @benjamn mentioned, this would primarily require extending recast to pretty print CSS ASTs, and create type definitions for the AST nodes.

Wrt to jscodeshift, most generic search and replace methods could still be used and adding CSS specific ones would be easy with a plugin.

@benjamn, what do you think about making recast accept a pretty printer? And how easy is it these days to load custom AST type definitions?

**Comment by ArmorDarks** [comment]
Sorry to see how that noble idea died,,,

**Comment by creatyvtype** [comment]
👎

**Comment by ycjcl868** [comment]
you can use [postcss](https://www.npmjs.com/package/postcss) to transform the styles files, something different in I/O operation.

**Comment by skovy** [comment]
I ran into a similar problem (wanting to transform CSS) and ended up using PostCSS as some of the comments in this issue suggest. I couldn't find any resources to get started so I turned it into a quick blog post if anyone else stumbles across this issue and is looking to codemod CSS: https://www.skovy.dev/blog/css-codemods-with-postcss.

**Comment by danieldelcore** [comment]
Hey folks, it is possible to do as suggested above via PostCSS. 

Here's an example: 


```ts

const plugin = (): Plugin => {
  const processed = Symbol("processed");

  return {
    postcssPlugin: "UsingTokens",
    Declaration: (decl) => {
      // Transformation goes here
    },
  };
};

export default async function transformer(file: FileInfo) {
  return await postcss([plugin()]).process(file.source).css;
}
```

The main downside with this approach is that you aren't able to leverage the "API" & AST of jscodeshift and recast. So you will need to rely solely on PostCSS. Also since jscodeshift uses dependency injection to expose it's API, distributing 
 codemods that use dependencies may be problematic. 

An idea for jscodeshift future architectural direction could be to refactor the "Runner" to be generic and allow authors of transforms to import the AST/Transformation library of choice.
