### ISSUE TITLE
Handle default parameters with flow types

### ISSUE THREAD

**Issue by ForbesLindesay** [facebook/jscodeshift#127]
Input:

```js
const myObj = {
  method: function (foo: number = 10) {
    return foo;
  },
};
```

Tranform:

```js
module.exports = (file, api, options) => {
  const j = api.jscodeshift;
  const printOptions = options.printOptions || {quote: 'single'};
  const root = j(file.source);


  const canBeSimplified = (key, value) => {
    return key.type === 'Identifier' && value.type === 'FunctionExpression';
  };

  root
    .find(j.Property)
    .filter(p => canBeSimplified(p.value.key, p.value.value))
    .forEach(p => {
      p.value.method = true;
    });

  return root.toSource(printOptions);
};
```

Current (broken) Output:

```js
const myObj = {
  method(= 10) {
    return foo;
  },
};
```

Expected output:

```js
const myObj = {
  method(foo: number = 10) {
    return foo;
  },
};
```

**Comment by hzoo** [comment]
lol what! I encountered this issue too and mentioned it in the babel slack - made https://github.com/babel/babylon/issues/67

**Comment by ForbesLindesay** [comment]
Yes, you can see what I'm working on at https://github.com/cpojer/js-codemod/pull/52

I'm trying to get it accurate enough to run at Facebook.

**Comment by fkling** [comment]
If this is a problem with the printer, which it seems to be, please report this on the recast repo.

**Comment by hzoo** [comment]
I found an issue with babylon (6 at least) since the location info isn't correct in that case - link ^

**Comment by danez** [comment]
@ForbesLindesay can you try again with the latest babylon version? It should be fixed now.

**Comment by fkling** [comment]
This works fine for me using the flow parser: http://astexplorer.net/#/qwFZM9gYRi .

Doesn't work with `babylon` because recast doesn't seem to be able to handle `ObjectProperty`.
