### ISSUE TITLE
Transform can no longer use Flow annotations

### ISSUE THREAD

**Issue by bhosmer** [facebook/jscodeshift#129]
After (I believe) [the change to allow multiple parsers](https://github.com/facebook/jscodeshift/commit/327f985598784e1e91615d78237ece490995d165), the transform code itself can no longer use Flow syntax. E.g. [this transform](https://github.com/flowtype/flow-codemod/tree/master/transforms/strict-type-args) now fails with the error:
```
SyntaxError: /Users/bhosmer/gh/flow-codemod/transforms/strict-type-args/strict-type-args.js: The keyword 'interface' is reserved (21:0)
  19 | // minimal API type info in lieu of full libdef
  20 | //
> 21 | interface Collection {
     | ^
  22 |   find(type: Object, filter?: (node: Object) => boolean): Collection;
  23 |   filter(callback: (node: Object) => boolean): Collection;
  24 |   forEach(callback: (node: Object) => void): Collection;
    at Parser.pp.raise (/Users/bhosmer/gh/jscodeshift/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.parseIdentifier (/Users/bhosmer/gh/jscodeshift/node_modules/babylon/lib/parser/expression.js:1060:12)
    at Parser.pp.parseExprAtom 
...
```
By commenting out [this line](https://github.com/facebook/jscodeshift/blob/master/src/Worker.js#L56) I'm able to pick up a `.babelrc` colocated with the transform file, but it can't be resolved to a plugin at that location, for obvious reasons. I'm hoping I can restore the earlier behavior without adding a plugin install step for the codemod... happy to submit a PR if you can give me the basic recipe.

**Comment by bhosmer** [comment]
FYI, [the issue](https://github.com/flowtype/flow-codemod/issues/4) that alerted us to the new behavior.

**Comment by fkling** [comment]
Sorry for that, I fixed that by simply loading the babel type strip plugin.
