### ISSUE TITLE
[Traversals] Add `findInScope`

### ISSUE THREAD

**Issue by cpojer** [facebook/jscodeshift#13]
A `findInScope` method would only pattern match one scope level deep, beginning from the scope it was called on.

This is useful to find identifiers on a specific level in the AST, for example `arguments` or `this` inside of a function/method.

Examples where I did this manually or worked around this problem:
https://github.com/cpojer/js-codemod/commit/7502159ad4a2daa32fdc8f758d3cb79431ec333b
https://github.com/cpojer/js-codemod/commit/a20a5e15aa4c2a268b4ff9982aeb5459716da7e8

**Comment by fkling** [comment]
This can currently be solved via `collection.closestScope().find(...)`. Do you need an additional method for that?
