### ISSUE TITLE
Provide detailed reporting

### ISSUE THREAD

**Issue by jurassix** [facebook/jscodeshift#130]
I have the need to get a list of file paths that were modified when running jscodeshift on a directory. I don't see any API that would provide this. 

Are you open for a PR that would add more context to the [fileCounters](https://github.com/facebook/jscodeshift/blob/master/src/Runner.js#L143) object returned from Runner.js?

ref: jurassix/atom-refactoring-codemods#18

**Comment by jurassix** [comment]
I need more detailed reporting that just a list of what changed. I'll fork this lib, build out the features I need and open other issues to see if they would be good candidates for PR.

**Comment by fkling** [comment]
Thanks!
