### ISSUE TITLE
Use Jest snapshot testing in testUtils

### ISSUE THREAD

**Issue by Daniel15** [facebook/jscodeshift#135]
Jest 14 adds snapshot testing: https://facebook.github.io/jest/blog/2016/07/27/jest-14.html. One of the advantages is that it allows snapshots to be automatically updated by running `jest -u`.

Currently we manually load the expected result and compare with `toEqual`: https://github.com/facebook/jscodeshift/blob/master/src/testUtils.js#L68. I think this could be replaced with snapshot testing, avoiding the need for us to manually load the file containing the expected result.

**Comment by steveluscher** [comment]
Came here to post this. Do you think we should make a `defineSnapshotTest` utility, or just replace the implementation of `defineTest` to write and read snapshots from the `*.output.js` files?

**Comment by Daniel15** [comment]
I feel like we should update the existing utility to use snapshots. We need to ensure it's backwards compatible with the old version though, at least until everyone migrates across.

What about using the `output.js` file if it exists, and use `toMatchSnapshot` if it doesn't exist? This means that existing tests would continue working as-is, while existing tests would use snapshots.

**Comment by dogoku** [comment]
If anyone's interested, I made a PR (See above) with a simple integration with snapshots.

Two methods have been added for snapshots: 
- `defineSnapshotTest` to define a test that uses snapshots
- `runSnapshotTest` to just  execute just the assertion inside your own tests

Created snapshots are placed under `__tests__/__snapshots__` as per jest's default

**Comment by Hypnosphi** [comment]
Here's the link to @dogoku's PR https://github.com/facebook/jscodeshift/pull/297
