### ISSUE TITLE
Spawning 0 Workers - jscodeshift doesn't run in an environment with 1 CPU

### ISSUE THREAD

**Issue by daedalus28** [facebook/jscodeshift#136]
When running a codemod (lodash-codemods in particular), I see it finds files but then spawns 0 workers. 
Looking at the source code I believe it caused by this line: https://github.com/facebook/jscodeshift/blob/e03140df04c9914680b860209ed118fc7d9a8cba/src/Runner.js#L24
I'm running this in a docker container which only has 1 CPU - running `require('os').cpus()` in node in the same place returns an array with a single CPU, but `length - 1` in an environment like mine with 1 CPU will prevent it from running. Does jscodeshift simply require multiple CPUs, or can we change this behavior (with a flag or otherwise)?

**Comment by fkling** [comment]
Oh :D

We can definitely change it to use that one core when the machine only has one :)

**Comment by daedalus28** [comment]
Awesome - I'm happy to take a quick stab at a PR for it.

**Comment by fkling** [comment]
Released a new version: https://github.com/facebook/jscodeshift/releases/tag/v0.3.27 .
