### ISSUE TITLE
Cannot run over browser files

### ISSUE THREAD

**Issue by javivelasco** [facebook/jscodeshift#139]
Hi! Sorry if this sounds dummy, I'm have almost no experience with codemods. I have a large codebase of old legacy code. It's from an SPA that uses namespaces for organization with modules defined like:

```js
(function (app) {
  app.myModuleFunction = function() {
    // ...
  };
})(window.myapp);
```

I'm trying to run a simple codemod but I'm getting an error saying `window` is not defined. Is there any way to polyfill? Is it possible to run a codemod to transform some function calls inside that kind of code at all? 
Thanks!

**Comment by javivelasco** [comment]
Sorry, my bad 🍶

**Comment by fkling** [comment]
🐱

**Comment by Ianfeather** [comment]
@javivelasco How did you resolve this?

**Comment by javivelasco** [comment]
Sorry @Ianfeather, it was a dummy mistake on my side and I don't really remember it. It was like I wasn't running the updated script because I had two different editors opened or something like that, not related to codeshift at all :(
