### ISSUE TITLE
Make Collection.prototype.get fail gracefully when __paths.length === 0

### ISSUE THREAD

**Issue by DrewML** [facebook/jscodeshift#140]
I spent more time debugging this one tonight than I'd like to admit :). [Minimal Repro is here](http://astexplorer.net/#/zw3Y48cQ6T/1).

When calling `.get` on a collection without any paths, an exception is thrown. Unfortunately, because the exception message itself references `get`, I made the (poor) assumption that it was my call to `get`, not [the implementation's call to `path.get`](https://github.com/facebook/jscodeshift/blob/81ba196/src/Collection.js#L173-L176).

Would you be willing to accept a PR to change the behavior here? I think either returning a falsy value (maybe `null`, similar to `document.querySelector`) or throwing a more specific error (encouraging the user to check `Collection.prototype.size` first) would work.

**Comment by fkling** [comment]
I would certainly accept a pull request to improve this 😃 .

Which behavior would you prefer? I feel like throwing an error might be more helpful?

**Comment by DrewML** [comment]
> I feel like throwing an error might be more helpful?

Yeah, I think you're right. Returning something would probably still lead to less-than-helpful failures anyway, since code will likely chain off of `get`.

I'll submit a PR for that change.
