### ISSUE TITLE
API docs generated?

### ISSUE THREAD

**Issue by jayphelps** [facebook/jscodeshift#144]
I see the source uses jsdoc-style comments, but do not see any documentation from these built anywhere. Am I missing it or is that just a TODO?

One of the reasons for lack of adoption I've heard from others is that it's not obvious what built-in helps exist and how to use them, other than digging through the source/tests.

**Comment by DrewML** [comment]
FWIW, there is also #22 that discusses auto-generated docs.

**Comment by fkling** [comment]
No one has done it yet 😃  If someone wants to take a stab at it I'm happy to review it.

I agree that we should definitely have docs ideally with proper examples.

**Comment by jayphelps** [comment]
I had searched, but some how missed #22. Will defer to that ticket.
