### ISSUE TITLE
Got errors when using babylon

### ISSUE THREAD

**Issue by ChrisFan** [facebook/jscodeshift#145]
Got errors when using babylon as my parser:

```bash
jscodeshift -t src/transform.js demo -d --ignore-config demo/.gitignore --extensions js,jsx --parser babylon
```

Errors:
```
ERR demo/proxy.config.js Transformation error
Error: did not recognize object of type "ObjectProperty"
    at Object.getFieldNames (/Users/kada/Chris/dva-ast/node_modules/.0.9.0@ast-types/lib/types.js:663:19)
....
 ERR demo/src/components/Connect.jsx Transformation error
Error: did not recognize object of type "StringLiteral"
    at Object.getFieldNames (/Users/kada/Chris/dva-ast/node_modules/.0.9.0@ast-types/lib/types.js:663:19)
```

**Comment by DrewML** [comment]
I ran into a similar issue working on [this](https://github.com/reactjs/react-codemod/issues/64#issuecomment-239658978).

My understanding is that this isn't a bug in `jscodeshift` itself, but rather an update needed downstream in the `ast-types` project to account for places where `Babylon` diverges from `ESTree`. More discussion [here](https://github.com/benjamn/ast-types/issues/132).

**Comment by ChrisFan** [comment]
@DrewML thx

Looks like we have to wait for the updating of ast-types.

**Comment by fkling** [comment]
Yep, @DrewML is right. You could use the flow parser instead, which is estree compatible.
