### ISSUE TITLE
Printing bug possibly related to flow + property initializers

### ISSUE THREAD

**Issue by camspiers** [facebook/jscodeshift#147]
I'm attempting to transform a file that happens to have property initialized functions. Using the transform:

```js
export default function transformer(file, api) {
  const {jscodeshift: j} = api;

  return j(file.source)
    .findJSXElementsByModuleName('Button.react')
    .forEach(a => {
      a.get('openingElement').get('name').replace('ReplacementButton');
    })
    .toSource();
}
```

I'm transforming:

```js
'use strict';

const React = require('React');
const Button = require('Button.react');

class Example extends React.PureComponent {
  render(): ReactElement<any> {
    return <Button size="large" />;
  }

  _exampleFunction = (): void => {};
}

class Example2 extends React.PureComponent {
  render(): ReactElement<any> {
    return <Button size="large" />;
  }
}

module.exports = Example1;
```

When `_exampleFunction` is present, the transform will fail to transform the second `Button` instance, but when absent things work as expected.

When transforming some even larger more complex files (that have property initializer functions) I run into an issue where the outputted file ends up containing syntax errors.

**Comment by fkling** [comment]
Is this a code generation or a parsing issue? If the former, then it's likely an issue with recast.

Which parser are you using? Have you tried using the flow parser? You can either pass `--parser=flow` to the command or add `export const parser = 'flow';` to the transform.

**Comment by camspiers** [comment]
Hey @fkling sorry I didn't include it in the report, but this was using the flow parser.

**Comment by fkling** [comment]
So, looking at the astexplorer output for recast + flow, it's clear that the parser doesn't generate the correct AST. 

Using flow alone works fine. Now I have to find out whether we are using an older version of flow with recast / jscodeshift or whether recast is doing something to the AST.

**Comment by camspiers** [comment]
The flow-parser version I'm using is 0.28.0
