### ISSUE TITLE
Error {…} does not match type string when adding expression

### ISSUE THREAD

**Issue by soswow** [facebook/jscodeshift#161]
I found this stackoverflow issue and @fkling suggested that author submits an issue. I can't find this issue and I experience similar issue. I am stuck with that.

Working example is here: https://astexplorer.net/#/P6euf9XIlR/1

Author's source:
```javascript
/**
 * Paste or drop some JavaScript here and explore
 * the syntax tree created by chosen parser.
 * You can use all the cool new features from ES6
 * and even more. Enjoy!
 */
var x = 0;
var y = 2;

if (x < 10) {
  x = y * 2;
  console.log("x")
}
```
Transformer:
```javascript
export default function transformer(file, api) {
  const j = api.jscodeshift;
  const {expression, statement, statements} = j.template;

  var testBinary = j.binaryExpression("==",j.literal(2),j.literal(3)) 
  
  return j(file.source)
    .find(j.IfStatement)
  	.insertBefore(testBinary)
    .toSource();
};
```
Error:
```
{operator: ==, left: [object Object], right: [object Object], loc: null, type: BinaryExpression, comments: null} does not match type string
```

In my case I have code like:
```javascript
const testModuleDescribeNodePath = jscodeshift.callExpression(
    jscodeshift.identifier("describe"), []
);

QUnitModuleCallExpressions
    .closest(jscodeshift.ExpressionStatement)
    .insertBefore(testModuleDescribeNodePath);
```
With exception:
```
Error: {callee: [object Object], arguments: , loc: null, type: CallExpression, comments: null} does not match type string
```

**Comment by soswow** [comment]
It seems like in my case wrapping with `j.expressionStatement(` solved the problem.

**Comment by soswow** [comment]
ok. I think I got it. I should ether replace ExpressionStatement with another ExpressionStatement (so I need to wrap my callExpression with j.expressionStatement()) or I can replace callExpression with another callExpression (no need to wrapping in expressionStatement)

**Comment by fkling** [comment]
Yeah, this pretty much looks like the same problem as #157. See my answer there how I think we could make this easier to debug (or even handle it automatically).
