### ISSUE TITLE
How do I add comments to a file?

### ISSUE THREAD

**Issue by pbomb** [facebook/jscodeshift#167]
I'm writing a code generation transform using jscodeshift. I'm creating a variableDeclarator (as a blockStatement inside a functionExpression) and wanting to attach a comment to the preceding line, but struggling to get it to work. I see lots of examples of copying comments from existing nodes to new nodes, but not how to create a new comment.

Could somebody explain how to do this? Thanks!

**Comment by DrewML** [comment]
[Here](http://astexplorer.net/#/nmno5f20v6) is a quick example of adding a leading comment

**Comment by fkling** [comment]
We could consider providing methods to make this a bit easier, e.g. `.addLeadingComment`, `.addTrailingComment`.

However, jscodeshift itself doesn't have much control over how comments are printed, e.g. it seems inserting a comment with the technique @DrewML mentioned can result in something like

```js
const a = /*foo*/
1;
```

where one probably would expect

```js
const a = /*foo*/1;
```

**Comment by pbomb** [comment]
great, thanks! I hadn't seen the `commentLine` function, but will give that a shot. I'll close this issue if that works.

I'm still not sure where to go to find the available functions. I usually go [here](https://github.com/benjamn/ast-types/tree/master/def) and look at the core and flow pages. CommentLine shows up on the `babel` page. Is there a good place to go to explore the jscodeshift API?

**Comment by fkling** [comment]
Currently the best place is probably in astexplorer using the auto completion via CTRL+space.

**Comment by pbomb** [comment]
`j.commentLine` works great, I'm closing this issue.

Also, @fkling, thanks for the astexplorer reference. That's a great resource!

**Comment by dashokkumar93** [comment]
How to add comment at the end of the line for a variable declaration. Is there any methods available?
In this [codemod](http://astexplorer.net/#/gist/f2a50b60925121d42ca3cc6fc2094f45/a9864a2485944b363cf29b0570a34d570f8de713) . i want `const a = 1, b = 2;` to be transformed into `const a = 1, b = 2; //custom comment`.  How to achieve this?

**Comment by fkling** [comment]
@dashokkumar93, for future reference,  https://github.com/facebook/jscodeshift/issues/167#issuecomment-370139182 might be useful.
