### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by pengxueshan** [facebook/jscodeshift#169]
system: macos 10.12.1
node: 6.9.1
npm: 3.10.8

1. npm install -g jscodeshift
2. jscodeshift --help
3. zsh: command not found: jscodeshift

**Comment by keyanzhang** [comment]
Is your npm installed properly? I just did a fresh installation locally and it worked. Please `echo $PATH` to check your `PATH` setup. http://stackoverflow.com/a/14840304/2582421

**Comment by pengxueshan** [comment]
@keyanzhang   谢谢，问题已解决。是npm安装目录的问题
