### ISSUE TITLE
Deprecated dependency: nomnom

### ISSUE THREAD

**Issue by nickmccurdy** [facebook/jscodeshift#170]
As of Sep 9, 2015, [nomnom](https://github.com/harthur/nomnom) has been marked as deprecated. The author recommends switching to [commander.js](https://github.com/tj/commander.js).

**Comment by golgistudio** [comment]
And the license for nomnom is 'None' - makes it hard for those organizations that do license checks on  package sub dependencies.  (this package is used by storybook/cli)

**Comment by mbrookes** [comment]
jscodeshift triggers dependency warnings on tidelift.com / https://libraries.io/npm/nomnom

There is a maintained version of nomnom here: https://github.com/GerHobbelt/nomnom

**Comment by fkling** [comment]
I went with implementing our own version (a2becc5cf9263c3fe675218e059a181c35ce7060).
