### ISSUE TITLE
Can't handle Flow's <*> syntax

### ISSUE THREAD

**Issue by graue** [facebook/jscodeshift#172]
In Flow, if I have a parameterized type `MyType<T>`, I can annotate something as `MyType<*>` to tell Flow to infer the parameter. This construction causes jscodeshift to error, unfortunately. There's probably a dependency needing to be upgraded.

**Comment by DrewML** [comment]
Not at a computer atm so I can't test, but did you try running the CLI with '--parser=flow'?

**Comment by fkling** [comment]
As @DrewML said, try to use the flow parser. By default jscodeshift will use Babel v5 which doesn't support newer flow features.
