### ISSUE TITLE
ignore-pattern working weirdly

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/jscodeshift#178]
Hi,

I have a script working with jscodeshift, it calls jscodeshift two times, once with ./ as path, another time with several paths as relatives parents (../app ../websites/ ...).

I call it with --ignore-pattern="node_modules/", I've also tried "**/node_modules/**/*" and many others, but everytime it doesn't ignore a lot of files in node_modules in relative ones (eg : ../app/node_modules/module/something.js).

Do I use it well ? If yes, what's the problem with the matching system ? I've analysed sources of jscodeshift and mm, but nothing revelant for solving the issue.

Thank you

**Comment by gorjuspixels** [comment]
Use `--ignore-pattern="node_modules/*"`.
