### ISSUE TITLE
recast@^0.11.11 is broken

### ISSUE THREAD

**Issue by ReinAkane** [facebook/jscodeshift#188]
Either upgrade to `0.12` or clamp to `0.11.22`. The most recent `0.11` point release does not accept `babel-core` as a parser, throwing an error `options.parser.parse is not a function` whenever codeshift is invoked.

**Comment by fkling** [comment]
Thanks, I'll look into it. In the meantime you can just reinstall jscodeshift to get a higher recast version (might have to explicitly remove recast).

**Comment by ReinAkane** [comment]
@fkling to be clear, reinstalling jscodeshift gives me the broken version (`0.11.23`) because that is the most recent version that matches [the jscodeshift package.json](https://github.com/facebook/jscodeshift/blob/master/package.json#L43).

Workaround is to specify `"recast": "0.11.22"` in a consuming project's project.json.

**Comment by fkling** [comment]
Oh I see. I got confused with the title. I thought 0.11.11 was broken. Thanks for the clarification!

**Comment by ReinAkane** [comment]
Upon further testing, I have discovered that this is not related to `jscodeshift` (or `recast`) but was due to my using babel 6, and the fact that reinstalling `recast` caused `jscodeshift` to get bundled dependencies under npm 3 (not sure why...).

Sorry about the bad bug report!

**Comment by fkling** [comment]
No worries! Dependencies are hard.
