### ISSUE TITLE
Union types within an array type lose parens 

### ISSUE THREAD

**Issue by robz** [facebook/jscodeshift#191]
The following: 

 ```
 j.arrayTypeAnnotation(
   j.unionTypeAnnotation([
     j.stringLiteralTypeAnnotation('a', 'a'),
     j.stringLiteralTypeAnnotation('b', 'b'),
   ])
 )
```

should output:

```
("a" | "b")[]
```

but instead outputs

```
"a" | "b"[]
```

which parses as

```
 j.unionTypeAnnotation([
   j.stringLiteralTypeAnnotation('a', 'a'),
   j.arrayTypeAnnotation(
     j.stringLiteralTypeAnnotation('b', 'b'),
   ),
 ])
```

because `[]` has a higher precedence than `|`. 

The same occurs for intersection types (`&`).

http://astexplorer.net/#/gist/428ddb0b4f413ec4cff8bb86216ba36c/634e60144fc07d0c549c4221ae4d0464e656ae8a

**Comment by fkling** [comment]
All the printing is done by recast (https://github.com/benjamn/recast), please file a bug report there.
