### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by phaistonian** [facebook/jscodeshift#192]
Hello.

`jscodeshift   -d -t ../react-codemod/transforms/React-PropTypes-to-prop-types.js js`

gives

> ERR js/apps/UserList/index.js Transformation error
> TypeError: Cannot read property 'name' of undefined

for 

```js
import React, { PropTypes } from 'react';
import { Provider } from 'react-redux';

import configureStore from './store/configureStore';
import App from './containers/App';

const UserList = ({ initialState }) => <Provider
  store={configureStore(initialState)}>
  <App />
</Provider>;

UserList.propTypes = {
  initialState: PropTypes.object,
};

export default UserList;
```

Ideas ?:)

**Comment by jch254** [comment]
Check this out: https://github.com/reactjs/react-codemod/pull/106

**Comment by fkling** [comment]
I guess this was fixed / discussed in https://github.com/reactjs/react-codemod/pull/106 .
