### ISSUE TITLE
Update Babel-Core to avoid minimatch issues on CI builds

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/jscodeshift#197]
I get this error:
![skjermbilde 2017-05-25 kl 12 38 20](https://cloud.githubusercontent.com/assets/16735925/26447060/10ad6a70-4147-11e7-842a-930003093de5.png)
Along the CI build at:

https://circleci.com/gh/webpack/webpack/840?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Any way you could bump dependencies?

**Comment by fkling** [comment]
See my explanation at https://github.com/facebook/jscodeshift/pull/198#issuecomment-304329657
