### ISSUE TITLE
jscodeshift blows up on some Flow Union Types 

### ISSUE THREAD

**Issue by TheSavior** [facebook/jscodeshift#207]
jscodeshift blows up when a flow union type is defined with a `|` at the beginning:

```
type Foo = 
  | 'bar'
  | 'baz';
```

It doesn't when it is written like this:

```
type Foo = 
  'bar'
  | 'baz';
```

The first syntax is valid according to flow: https://tryflow.org/?code=dHlwZSBGb28gPSAKICB8ICdiYXInCiAgfCAnYmF6Jzs=

![screen shot 2017-06-21 at 1 41 47 pm](https://user-images.githubusercontent.com/249164/27405705-7a74e0be-5687-11e7-9a5c-f44765b083f7.png)

https://astexplorer.net/#/gist/c85f1d6651c8fbbb26231ec8833786d9/176effc1a4c27731e34b7ddaed76fa4859893b28

**Comment by fkling** [comment]
jscodeshift uses babel v5 as parser by default. To use the flow parser (which can understand this syntax) pass `--parser=flow` to the CLI or `export const parser = 'floe';` from the transform.

**Comment by TheSavior** [comment]
Neat!
