### ISSUE TITLE
Question: How to transform comments?

### ISSUE THREAD

**Issue by namirsab** [facebook/jscodeshift#212]
I have a transform that changes some functions, but those are documented with JSDOC and I'd like to also change the jsdoc.

Is there any way to do this?

Thanks in advance :smile:

**Comment by alangpierce** [comment]
@namirsab every comment gets associated with some node (I'm not sure what the exact rules are), and every node has an optional has a `comments` field with those comments. As with other AST nodes, you can modify comments as part of your transform or generate new comments.

Here's an example to get you started:
http://astexplorer.net/#/gist/8c7d9f81226bbbdee5d9c7a2468ddaa0/c3d93b44e2bf90e0ff2553ec1c8d85dd2daf807e

**Comment by namirsab** [comment]
@alangpierce thanks a lot :smile:

I've been learning a lot with the AST Explorer, but I miss better docs. Any way to help?

**Comment by alangpierce** [comment]
As far as I know there aren't any great docs. 😕

Some stuff I've done to learn: 
* I initially got started by reading this tutorial: https://www.toptal.com/javascript/write-code-to-rewrite-your-code
* AST Explorer is nice for understanding the AST format. You can dig into the AST on the right and see what's there. You might have been able to dig through and find comments there, for example. You can also `console.log` anything and look at the value and prototype in the Chrome console to get a better sense of what you can do with any particular thing (and autocomplete is helpful).
* I have the jscodeshift and recast repos on my machine and sometimes dig through them to figure out what functions are there and what I have access to.
* There are also plenty of examples out there to look at, e.g. https://github.com/facebook/jscodeshift#example-codemods

**Comment by namirsab** [comment]
@alangpierce thanks, i've done the same to learn :smile: 
What I meant with my previous comment is if there is any repo or any project to add better documentation to `jscodeshift` so other people don't need to do the same (even though ASTExplorer is a must, in any case)

Anyway, let's close this issue as it's not related with the initial topic anymore.

**Comment by alangpierce** [comment]
To my knowledge, there aren't any efforts to improve the documentation right now, but I'm sure it would be a welcome contribution. 😄
