### ISSUE TITLE
Can only add methodDefinition to objectExpression via replaceWith

### ISSUE THREAD

**Issue by ltegman** [facebook/jscodeshift#224]
In my use case I am trying to constuct an object with method shorthand properties on it. I found I was able to do this without issue when I was simply replacing an existing Property using `replaceWith`, but constructing a new ObjectExpression with a MethodDefinition in the properties array throws and error. Here's some snippets of what I'm talking about:

Goal output:
```javascript
const myObject = {
  myMethod() {}
}
```

Using replaceWith (working):
```javascript
j(j.objectExpression([j.property('init', j.identifier('junk'), j.objectExpression([]))]))
  .find(j.Property)
  .replaceWith(j.methodDefinition('method', j.identifier('myMethod'), j.functionExpression(null, [], j.blockStatement([]))
  .toSource();
```

Using the objectExpression builder (not working):
```javascript
j.objectExpression([
  j.methodDefinition('method', j.identifier('myMethod'), j.functionExpression(null, [], j.blockStatement([])
])
```

This is the error message I receive when attempting it through pure building (last snippet):
```
[{kind: method, key: [object Object], value: [object Object], static: false, loc: null, type: MethodDefinition, comments: null, computed: false, decorators: null}] does not match field "properties": [Property | ObjectMethod | ObjectProperty | SpreadProperty] of type ObjectExpression
```

I should mention I would build an ObjectMethod instead of a MethodDefinition, but I didn't see an option for that on the api.

For now it's easy enough to workaround with the replaceWith method, just wanted to get this out there in case anyone has a chance to look into it. I'd be happy to spend some time on it myself, but I'm very new to the jscodeshift world, so I imagine it would be slow going.

Thanks for your time and effort!

**Comment by rajasegar-c** [comment]
@ltegman Is it fixed now, do you have any workarounds for new creating methods

**Comment by fkling** [comment]
@rajasegar-c: The `objectMethod` build is available and works like this:

```
j.objectExpression([
  j.objectMethod('method', j.identifier('myMethod'), [], j.blockStatement([]))
])
```

Output:

```
{
    myMethod() {}
}
```

https://astexplorer.net/#/gist/cc6c1195f04ddfb4eb5c06dadd7ba07b/3ad1ede57725b287eb039fb3dff86f0883b4d9b2
