### ISSUE TITLE
Reactiflux doesn't have a #codemod channel

### ISSUE THREAD

**Issue by nickmccurdy** [facebook/jscodeshift#243]
The [Support](https://github.com/facebook/jscodeshift#support) section of the readme seems to link to a Reactiflux channel that no longer exists. Has this moved to another server or should we change the wording to point to Reactiflux's #tooling channel?

**Comment by sjy** [comment]
it seems to be linked to the home page 
![image](https://user-images.githubusercontent.com/1523060/37267213-bab99664-25f9-11e8-9ab1-b57ef0b55d56.png)
