### ISSUE TITLE
How to parameterize transforms from jscodeshift command line?

### ISSUE THREAD

**Issue by blaster151** [facebook/jscodeshift#248]
I cannot find a way to do this.  I have a "reusable" transform that wants to receive a parameter and its usage would be something like:

```
jscodeshift -t removeService.js *.ts -serviceNameToRemove DumbLegacyService
```
And then inside the transform I would like to access the value that was provided for `serviceNameToRemove`.  Am I missing an easy way to do this?

**Comment by tarjei** [comment]
Yes :) https://github.com/facebook/jscodeshift#options

**Comment by blaster151** [comment]
Thank you, @tarjei!
