### ISSUE TITLE
Remove blank lines

### ISSUE THREAD

**Issue by froxCZ** [facebook/jscodeshift#249]
Hi, is it possible to remove blank lines from import statements?
Imagine I have following:
```
/* @flow */
import fs from 'fs'
import fsb from 'fsb'

// comment
import config1 from './config'

import config2 from './config'
```

I would like to produce:
```
/* @flow */
import fs from 'fs'
import fsb from 'fsb'
// comment
import config1 from './config'
import config2 from './config'
```

Is it possible to achieve with jscodeshift and recast or should I look into something like cst? I inspected the recast ast node and it has no property denoting leading/trailing lines :(

Thanks

**Comment by fkling** [comment]
Yep, empty lines are not really part of the AST. A possible workaround could be to find  the position of `import` statements from the AST, and then look at the whole source code string if the previous character(s) are line breaks? It's not pretty but may work.
