### ISSUE TITLE
jscodeshift fails to build with React apps

### ISSUE THREAD

**Issue by luminaxster** [facebook/jscodeshift#253]
Hi there,
I'm trying to build my app(wrapped with react-create-app) for deployment(npm run build) and ran into this:

Failed to minify the code from this file: 
        ./node_modules/jscodeshift/src/Collection.js:32 
Read more here: http://bit.ly/2tRViJ9

Is there a known fix to this? I looked everywhere but ejecting seems to be the only way.

**Comment by fkling** [comment]
Unclear what the problem is here. I can successfully bundle jscodeshift with astexplorer.
