### ISSUE TITLE
Asynchronous code in transformers

### ISSUE THREAD

**Issue by akiran** [facebook/jscodeshift#254]
Is it possible to support asynchronous code in the transformers.

Our transformations depend on the data from database. We couldn't add asynchronous  code in transformers. I added async on the transformer function to use await inside transformer code. 
But it didn't work

**Comment by sibelius** [comment]
have you figure it out how to solve this?

**Comment by akiran** [comment]
@sibelius No, I didn't figure this out

**Comment by mattkime** [comment]
I'd also like to see this. I'm using https://github.com/Galooshi/import-js to resolve import statements but this isn't possible due to a lack of async function support.

**Comment by danieldelcore** [comment]
Hey all, I think this issue be closed now since merging this PR: https://github.com/facebook/jscodeshift/pull/237
