### ISSUE TITLE
babel-preset-es2015@6.24.1 Deprecation warning

### ISSUE THREAD

**Issue by AliSawari** [facebook/jscodeshift#259]
This package has been deprecated according to babel.

> warning webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by oculus42** [comment]
This issue duplicates #222 and is related to #246 
There is an open PR #247 for this.

Please close this issue in favor of the existing ones.

**Comment by AliSawari** [comment]
Will do
Thanks :+1:
