### ISSUE TITLE
nomnom@1.8.1: Package no longer supported.

### ISSUE THREAD

**Issue by AliSawari** [facebook/jscodeshift#260]
> warning webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

**Comment by AliSawari** [comment]
@christophercr Yeah I saw that too!
do you get this warning too? I use webpack-cli@2.1.3 and webpack@4.8.3
which is both installed by a `package@latest` format

**Comment by oculus42** [comment]
This also relates to #246

**Comment by AliSawari** [comment]
@oculus42 thanks!
