### ISSUE TITLE
Possible suggestion on how to switch from flow types in comments to regulat flow types

### ISSUE THREAD

**Issue by doberkofler** [facebook/jscodeshift#266]
I'm looking for a way to transform code using flow type definitions within comments to the regular ones.
Example: transform `let n/*: number*/ = 7;` to `let n: number = 7;`.

Does someone maybe already know of a solution to this or something similar to start with?

**Comment by fkling** [comment]
There isn't really an elegant way to do this. And it may not be easy to do for all type comments. But here is an example for how it could be done:

```
      if (path.node.comments[0].value === ': number') {
          path.node.typeAnnotation = j.typeAnnotation(j.numberTypeAnnotation());
          delete path.node.comments;
      }
```

https://astexplorer.net/#/gist/0c6474f0fa212c0222cc52b16becc43e/3a214a3fefb60dd837a6073caf14ce3f27fc1ee4
