### ISSUE TITLE
SyntaxError: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead 

### ISSUE THREAD

**Issue by huhuanming** [facebook/jscodeshift#274]
when I refactor my code by jscodeshift as folloing,
```shell
jscodeshift -t ~/react-codemod/transforms/sort-comp.js  --extensions js,jsx --parser babylon -   tatic
```

I get error like this.

```
SyntaxError: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead 
```

my component is a class with  decorator

```
@connect(homeSelector)
export default class HomePage extends React.PureComponent {
    // something
}
```

so how can I  fix this? 😳

**Comment by amitksingh1490** [comment]
https://github.com/facebook/jscodeshift/pull/284 this PR have changes to fix above issue.
Till the time this PR is not merged you can use https://github.com/amitksingh1490/jscodeshift/tree/SyntaxError-Using-the-export-keyword-between-a-decorator-and-a-class-is-not-allowed.-Please-use-%60export-%40dec-class%60-instead
above forked branch

**Comment by fkling** [comment]
You can now pass your own parser configuration to babylon via the `--parser-config` option. E.g.

```
jscodeshift -t ~/react-codemod/transforms/sort-comp.js  --extensions js,jsx --parser babylon --parse-config ~/parser-config.json
```

Have a look at https://babeljs.io/docs/en/babel-parser#options for all the options. You probably want to set the `decorators-legacy` or `['decorators', {decoratorsBeforeExport: true}]` options.
