### ISSUE TITLE
Find Immediate Children

### ISSUE THREAD

**Issue by trentrand** [facebook/jscodeshift#283]
Is there a method similar to `Find` but that only queries for immediate children?

If not, is there another means of retrieving these results? 

The naive solution is to simply filter a collections children.

# Example
```
static propTypes = {
  propA: PropTypes.shape({
    childProp: PropTypes.any
  }),
  propB: PropTypes.string
}
```

If I use `Find(j.Property)`, it gets all three Properties; I only want the root Properties `propA` and `propB`.

**Comment by fkling** [comment]
No there isn't. We could consider adding one, but I'm not sure how intuitive it is. The way AST nodes are nested is not necessarily clear to everybody. E.g. the statements inside a function are not children of the function but of the `BlockStatement` that is its `body`.

Your case it relatively simple though. `Property`'s are children of the `ObjectExpression`, so if `path` is `NodePath` to the `ObjectExpression`, so a filter would indeed work:

```js
j(path)
  .find('Property')
  .filter(p => p.parentPath.node === path.node)
```

https://astexplorer.net/#/gist/c467a08588fcdc961a40b66c24891410/0e7332bbcca7c18b77a5704e32f1bc8ab02dc3c8

**Comment by trentrand** [comment]
Thanks @fkling.

Your example worked for a ClassProperty, but not for an ExpressionStatement (e.g. `MyComponent.propTypes = { a: PropTypes.any }`).

I was able to tweak your example in order to make it work for both forms:

```
collection
  .find(j.ObjectExpression)
  .at(0)
  .map(parentPath => {
    return j(parentPath)
      .find(j.Property)
      .filter(p => {
        return p.parentPath.node == parentPath.node;
      })
    .paths();
  })
```
