### ISSUE TITLE
How to get the source code corresponding to the NodePath

### ISSUE THREAD

**Issue by iWun** [facebook/jscodeshift#285]
hello, everyone.
I have a question, how to get the source code corresponding to the NodePath?
For example, `hello, ${person.name}`.
thanks.

**Comment by fkling** [comment]
You can pass the path to `jscodeshift` and call `toSource`, e.g.

```
console.log(jscodeshift(path).toSource());
```

https://astexplorer.net/#/gist/14b9d1eadbcd86dc6e338e5375f89063/03d9643c8b633c818219d40e6fa1ecb64b681c81

This will call recast's print method internally.
