### ISSUE TITLE
Extra Parentheses Around Object Destructuring Without Declaration

### ISSUE THREAD

**Issue by oculus42** [facebook/jscodeshift#288]
Extra parentheses are added around destructured object assignments not associated with a declaration.

When transformed, `({bad} = obj);` becomes `(({bad} = obj));`, `((({bad} = obj)));`, and so on.

Example Code:
```javascript
const foo = (obj) => {
  const {ok1} = obj;
  const [ok2] = ok1;
  let ok3;
  [ok3] = ok1;
  let bad;
  ({bad} = obj);
};
```

This happens even with an "empty" transform:
```javascript
module.exports = (file, api) => api.jscodeshift(file.source).toSource();
```

**Comment by fkling** [comment]
This shouldn't happen anymore with the latest version. Could you verify please?

**Comment by oculus42** [comment]
Looks good, thanks!
