### ISSUE TITLE
Improve/fix applying babel to the transformer

### ISSUE THREAD

**Issue by fkling** [facebook/jscodeshift#294]
**Note:** If you have problems running codemods and get Babel related errors, run jscodeshift with `--no-babel`.

---

The last change to `src/Worker.js` causes issues with `babel-register`. Passing module identifiers causes `babel-register` to look up those modules in the wrong places. Those modules should be `require`d instead.

Furthermore, we probably don't want to transpile most of ES2015 features since people probably use a Node version that supports those. `present-env` already supports this:

> If you want to compile against the current node version, you can specify "node": true or "node": "current", which would be the same as "node": process.versions.node.

https://babeljs.io/docs/en/babel-preset-env#targetsnode

but we should also include/exclude plugins based on the current node version.

**Comment by brieb** [comment]
Thank you for fixing this. So sorry for introducing this issue. Will keep this in mind for future reference. TIL.

Should we also add `/\/node_modules\//` to this ignore list?
https://github.com/facebook/jscodeshift/commit/cb92c488b1fd068dbbd8f87ae380d2d8b3383513#diff-e957a0672425b8dcfdcfe9f8cccf36f7
