### ISSUE TITLE
The `printOptions` option doesn't work as expected from the command line

### ISSUE THREAD

**Issue by keqingrong** [facebook/jscodeshift#298]
When I use the command below to pass a `printOptions` option to the transformer:

```sh
$ jscodeshift -t transform.js <file> --printOptions='{"quote":"double"}'
```

`options.printOptions` passed into the transform function, which is a string but not an object:

```js
export default function transform(file, api, options) {
  //  options.printOptions -> '{"quote":"double"}'
  const printOptions = options.printOptions || {quote: 'single'};
  
  // ...
  return root.toSource(printOptions);
}
```

Many transform files from [react-codemod](https://github.com/reactjs/react-codemod) or [js-codemod](https://github.com/cpojer/js-codemod/) take it as an object without parsing the JSON string beforehand. 

It looks like that [argsParser.js](https://github.com/facebook/jscodeshift/blob/master/src/argsParser.js#L210) doesn't handle the case. Or did I miss something?

**Comment by fkling** [comment]
Maybe that was something nomom did automatically. Will dig into this.

**Comment by fkling** [comment]
Looks like it did this for undefined options: https://github.com/harthur/nomnom/blob/master/nomnom.js#L454-L460

**Comment by keqingrong** [comment]
The latest version has solved my problem. Thank you!
