### ISSUE TITLE
Transform to decorators after export syntax

### ISSUE THREAD

**Issue by ssutar** [facebook/jscodeshift#304]
How to transform to decorators after export syntax? Since the TC39 decorators proposal is finalized to use decorators after export. Something like:
```
export default 
@dec1
@dec2('prop')
class A {}
```
Currently the transformation puts decorators before `export default`  Something like:
```
@dec1
@dec2('prop')
export default class A {}
```
I tried changing the parser options, upgrading recast, jscodeshift to latest but with no luck. Here are parser options I am using `parser.js`:
```
const babylon = require("@babel/parser");

const defaultOptions = {
  sourceType: "module",
  allowImportExportEverywhere: true,
  allowReturnOutsideFunction: true,
  startLine: 1,
  tokens: true,
  plugins: [
    "estree",
    "asyncGenerators",
    "bigInt",
    "classProperties",
    "classPrivateProperties",
    "classPrivateMethods",
    ["decorators", { decoratorsBeforeExport: false }],
    "doExpressions",
    "dynamicImport",
    "exportDefaultFrom",
    "exportNamespaceFrom",
    "functionBind",
    "functionSent",
    "importMeta",
    "logicalAssignment",
    "nullishCoalescingOperator",
    "numericSeparator",
    "objectRestSpread",
    "optionalCatchBinding",
    "optionalChaining",
    ["pipelineOperator", { proposal: "minimal" }],
    "throwExpressions"
  ]
};

module.exports = function(options = defaultOptions) {
  return {
    parse(code) {
      return babylon.parse(code, options);
    }
  };
};
```

Main transform `index.js` file:
```
const getParser = require("./parser");
module.exports = function transformer(file, api, opts) {
  ...
};

// Set the parser, needed for supporting decorators
module.exports.parser = getParser();
```

I could not find any difference between the ASTs for before and after decorators. So it should be just changing a config option, but not able to figure out what the option would be

**Comment by zhalice2011** [comment]
you can clone the repository and change /parser/babylon config like this
![image](https://user-images.githubusercontent.com/24289349/58620652-338fae80-82fa-11e9-91bd-7df69de46fc4.png)

use node start the transform

`$ node ./jscodeshift/bin/jscodeshift.js -t codeshift.js ./yourProject/ --parser babylon`

**Comment by ElonVolo** [comment]
Duplicate, more or less. Touches on same issues as facebook/jscodeshift#505.
