### ISSUE TITLE
--ignore-pattern doesn't work for node_modules

### ISSUE THREAD

**Issue by daveisfera** [facebook/jscodeshift#307]
Running `jscodeshift` on `node_modules` doesn't make sense. This issue indicates that it can be done using `--ignore-pattern`, but that doesn't work:
https://github.com/facebook/jscodeshift/issues/178

And this recommendation to use `xargs` doesn't work with large projects that have a large number of files:
https://github.com/facebook/jscodeshift/issues/53

It would be nice if `--ignore-pattern` worked or if `node_modules` could be ignored through an option in the input.

**Comment by blaster151** [comment]
I have been able to make it ignore node_modules with the following:

````
--ignore-pattern /node_modules/**
````

**Comment by daveisfera** [comment]
I just tried that and `node_modules` in sub-directories were still included, but this appears to have worked `**/node_modules/**`. (I had been trying just a single `*`, like `/node_modules/*` and `*/node_modules/*`).
