### ISSUE TITLE
`<type>expr` to `expr as type`

### ISSUE THREAD

**Issue by unki2aut** [facebook/jscodeshift#314]
I'm trying to replace all `TSTypeAssertion` to a `TSAsExpression` for type `any`.

IMHO that should look something like the following:
```js
root.find(j.TSTypeAssertion).replaceWith(path => {
  if (path.node.typeAnnotation.type === 'TSAnyKeyword') {
    return j.tsAsExpression(path.node, j.tsAnyKeyword());
  }
  return path.node;
});
```

Somehow the second parameter of `j.tsAsExpression` is not supported and I get the error
```
Error: no value or default function given for field "typeAnnotation" of TSAsExpression("expression": Expression)
```

What might I be doing wrong?

**Comment by fkling** [comment]
You are not doing anything wrong. This looks like a bug in `ast-types`. It looks like the type field is not settable via the builder: https://github.com/benjamn/ast-types/blob/master/def/typescript.ts#L73

I'd suggest to file a bug or PR for `ast-types`.

**Comment by unki2aut** [comment]
@fkling thx, will do :+1:

**Comment by ElonVolo** [comment]
fixed
