### ISSUE TITLE
API for custom parsers like glimmer / handlebars templates

### ISSUE THREAD

**Issue by rajasegar** [facebook/jscodeshift#315]
I have created a codemod within [astexplorer](https://astexplorer.net/#/gist/b128d5545d7ccc52400b922f3b5010b4/571266d8c29cb8eb1bd5730c0c388526081cce46) for transforming Handlebars curly brace syntax to Angle brackets syntax proposed by this RFC https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md
But i am unable to find any documentation or ref on how to convert this to a proper transform that can be executed by jscodeshift.
Here is the codemod repo
https://github.com/rajasegar/ember-angle-brackets-codemod
It is throwing a syntax error like this:
`ERR source.handlebars Transformation error (Cannot match against 'undefined' or 'null'.) TypeError: Cannot match against 'undefined' or 'null'. at syntax (/Users/user/Documents/www/emberjs/ember-angle-brackets-codemod/transform.js:24:56)`

**Comment by rajasegar** [comment]
This is how I ended up with so far. Please let me know if this is correct.
```js
const glimmer = require('@glimmer/syntax');
module.exports = function(fileInfo, api, options) {
  const ast = glimmer.preprocess(fileInfo.source);

  glimmer.traverse(ast, {
      MustacheStatement(node) {
        // Put your transform logic here
      },
      BlockStatement(node) {
        // Put your transform logic here
      }
  });
  return glimmer.print(ast);
};
```
Reference: https://github.com/rajasegar/ember-angle-brackets-codemod/blob/master/transforms/angle-brackets/transforms/angle-brackets-syntax.js

**Comment by fkling** [comment]
Just checking whether there is still an issue here. As you have noticed, you can use any tool to convert the source code inside a transform, you don't have to use the jscodeshift API. Can this be closed?

**Comment by rajasegar** [comment]
Yes @fkling Sure, it can be closed, Thanks!
