### ISSUE TITLE
Reopen programmatic use conversation

### ISSUE THREAD

**Issue by marvin-solano** [facebook/jscodeshift#318]
Hi all,

Just want to discuss the reasoning behind keeping this tool limited to a CLI. I think that generators can have a huge benefit over a tool like this if programmatical use is enabled.

**Comment by fkling** [comment]
Can you elaborate on what you mean with "generators" in this context? You can use jscodeshift programmatically, but maybe not in the way you want. Please explain what exactly you want to do.

**Comment by marvin-solano** [comment]
Yeoman, plop, hygen, etc, are examples of generators. What I did was to add the imports of the newly created files (services, controllers, routers, etc) to the "main" file. The problem that I am facing is, how can I run jscodeshift as part of my yeoman code.

```js
const Generator = require('yeoman-generator');

module.exports = class extends Generator {
  async prompting() {
    this.answers = await this.prompt([
      {
        type: 'input',
        name: 'servicename',
        message: 'Please provide a service name:',
      }
    ]);
  }

  writing() {
    this.fs.copyTpl(
      this.templatePath('template.service.js'),
      this.destinationPath(`./src/services/${this.answers.servicename}.service.js`),
      {
        servicename: this.answers.servicename
      }
    );
  }

  // RUN THE CODE TRANSFORMATION HERE
};
```

**Comment by marvin-solano** [comment]
After lots of testing I figured out the way of doing this, @fkling I would love to work on a PR to enhance the documentation of the library if you are ok with it.

**Comment by fkling** [comment]
That would be much appreciated! 😃

**Comment by vine77** [comment]
@marvin-solano Do you have any tips on what you figured out?

**Comment by vine77** [comment]
Something like this seems to work:

```js
const Runner = require('jscodeshift/src/Runner.js');

const inputFile = require('path').join(process.cwd(), 'input.js');
const transformFile = require('path').join(__dirname, 'transform.js');

Runner.run(transformFile, [inputFile]);
```

**Comment by lgandecki** [comment]
Thanks for the snippet @vine77!
For people googling, currently the Runner requires also an options object to work:

```javascript
Runner.run(transformFile, [inputFile], {});
```

otherwise you get an error:
```
 const cpus = options.cpus ? Math.min(availableCpus, options.cpus) : availableCpus;
                       
TypeError: Cannot read property 'cpus' of undefined

```

**Comment by danielo515** [comment]
I am more interested about how to wrap the cli from another cli. The cli already has a lot of nice things built in (path location, options handling, logging, etc) I just want to check some local stuff and then pass all the arguments to jscodeshift cli. Is there any easy way of doing that?
