### ISSUE TITLE
enable passing parameters to codemods

### ISSUE THREAD

**Issue by sibelius** [facebook/jscodeshift#319]
I'd like to send some options to transforms to make them behavior different based on parameters

is this possible?

**Comment by rajasegar** [comment]
@sibelius Yes, you can do that please refer [options](https://github.com/facebook/jscodeshift#options) sections in the README
```sh
$ jscodeshift -t myTransforms fileA fileB --foo=bar
```
options would contain `{foo: 'bar'}`.

**Comment by sibelius** [comment]
Thanks
