### ISSUE TITLE
[Request] sourcemap support

### ISSUE THREAD

**Issue by richardspence** [facebook/jscodeshift#322]
Any chance for sourcemap support? A cursory glance at recast it looks like it supports it (although it doesn't automatically load them)

**Comment by fkling** [comment]
Can you elaborate on the use case?

**Comment by richardspence** [comment]
Example: using jscodeshift to post-process a build process.

MyFile.ts -> Typescript compiler (tsc ./MyFile.ts --sourceMap) -> emits MyFile.js & MyFile.js.map

This will emit a sourcemap (.map) file as well as a comment in the js file (`//# sourceMappingURL=MyFile.js.map`)

If any jscodeshift operations are performed on MyFile.js, it would be beneficial for jsCodeshift to also load the sourcemap (if any), and emit an updated sourcemap.   This will allow debuggers to correctly correlate the line of code back to the original.  Webpack is a good example that will do this, and the emitted sourcemap generated correctly identifies webpack boilerplate code as well as user code.

Without this, the sourcemap will be incorrect and if loaded in a debugger will point to invalid locations in the original source.

It's also worth noting that sourcemaps can come in many forms, including being inlined (with original source) in the emitted file.  The example above uses external sourcemaps.
Examples:
## MyFile.ts
```ts
export class Foo{
    bar(){
        return 3;
    }
}
```
## Myfile.js
```js
"use strict";
exports.__esModule = true;
var Foo = /** @class */ (function () {
    function Foo() {
    }
    Foo.prototype.bar = function () {
        return 3;
    };
    return Foo;
}());
exports.Foo = Foo;
//# sourceMappingURL=MyFile.js.map
```
## MyFile.js.map
```map
{"version":3,"file":"MyFile.js","sourceRoot":"","sources":["MyFile.ts"],"names":[],"mappings":";;AAAA;IAAA;IAIA,CAAC;IAHG,iBAAG,GAAH;QACI,OAAO,CAAC,CAAC;IACb,CAAC;IACL,UAAC;AAAD,CAAC,AAJD,IAIC;AAJY,kBAAG"}
```

**Comment by pionxzh** [comment]
Hi @ElonVolo, may I know the status of this? Has this been implemented somewhere?

I tried searching in the codebase but had no luck.
