### ISSUE TITLE
"Raw" string instead of manually building complex nodes

### ISSUE THREAD

**Issue by mikob** [facebook/jscodeshift#326]
I've seen this "template" functionality: https://github.com/facebook/jscodeshift/pull/16

But it doesn't seem to work for property values? Is there any other way of inserting code as-is (as a string) without building the nodes out?

This doesn't work...

```
j.property('init', j.identifier(lang), j.template.statement(`input => "test"`));

Unexpected token, expected ";"
```

**Comment by fkling** [comment]
The value of a property cannot be a statement, it must be an expression. 

    j.property('init', j.identifier(lang), j.template.expression`input => "test"`);

should work

(note that `j.template.statement` and `j.template.expression` are tagged template functions).

**Comment by mikob** [comment]
I tried that as well, it's a similar error but with an unexpected ","

**Comment by fkling** [comment]
Maybe an issue elsewhere because it works here: https://astexplorer.net/#/gist/3c9f270caee5835a7f314592a9f8b3bb/46dd245b3bd642a1e92002808872b7bebfff37b6

**Comment by mikob** [comment]
I was using a function call, and not the template literal syntax. I wasn't aware of that feature until now, thanks!

**Comment by mikob** [comment]
sorry, should have read more carefully, just noticed you already specifically pointed that out.
