### ISSUE TITLE
Cannot build ImportDefaultSpecifier

### ISSUE THREAD

**Issue by kyldvs** [facebook/jscodeshift#33]
It always complains about a missing id which I'm not able to provide when I try to build it with functions. Using template I can get a little bit farther and then manually set the id. Not sure if this is an error on jscodeshift or a library that is being consumed by jscodeshift, but since I can repro in the AST explorer I'll just start by reporting here :)

http://felix-kling.de/esprima_ast_explorer/#/odivoefENV/1

**Comment by fkling** [comment]
Regarding printing: benjamn/recast/pull/209
Regarding building: have to investigate more

**Comment by benjamn** [comment]
Possibly related: https://github.com/benjamn/recast/issues/206

**Comment by fkling** [comment]
^ Ah, thank you. I haven seen that issue before :)

**Comment by cpojer** [comment]
This seems to have been resolved in recast?

**Comment by fkling** [comment]
Printing yes, but not building...

**Comment by cpojer** [comment]
@benjamn does building work yet?

**Comment by benjamn** [comment]
This should work as of https://github.com/benjamn/ast-types/releases/tag/v0.8.9, thanks to @marcioj.

**Comment by jedwards1211** [comment]
@benjamn I'm getting a similar error with with `exportSpecifier` in `jscodeshift` 0.11.0:

```
andy@Andys-MacBook-Pro-2:jscodeshift-find-imports (master) $ node
Welcome to Node.js v12.16.0.
Type ".help" for more information.
> var j = require('jscodeshift')
undefined
> j.exportSpecifier(j.identifier('foo'), j.identifier('bar'))
Uncaught:
Error: no value or default function given for field "exported" of ExportSpecifier("id": Identifier | null, "name": Identifier | null)
    at addParam (/Users/andy/codemodsquad/jscodeshift-find-imports/node_modules/jscodeshift/node_modules/ast-types/lib/types.js:443:27)
    at /Users/andy/codemodsquad/jscodeshift-find-imports/node_modules/jscodeshift/node_modules/ast-types/lib/types.js:477:21
    at Array.forEach (<anonymous>)
    at Function.builder [as exportSpecifier] (/Users/andy/codemodsquad/jscodeshift-find-imports/node_modules/jscodeshift/node_modules/ast-types/lib/types.js:475:46)
> 
andy@Andys-MacBook-Pro-2:jscodeshift-find-imports (master) $ npm ls recast
jscodeshift-find-imports@0.0.0-development /Users/andy/codemodsquad/jscodeshift-find-imports
└─┬ jscodeshift@0.11.0
  └── recast@0.20.3 
```
