### ISSUE TITLE
Missing parentheses around `LogicalExpression` when used in `optionalMemberExpression` builder

### ISSUE THREAD

**Issue by omninonsense** [facebook/jscodeshift#331]
Hello!

So I have a transform that transforms `a.getIn(['b', 'c'])` to `a?.b?.c` (and some more stuff). If instead of  `a` there is a binary expression (eg `a || x`), the transform fails (by not wrapping the binary expression in parentheses). I am not sure if I am doing something wrong here.

What I expect is `(a || x)?.b?.c`, but I get `a || x?.b?.c`

Here is an [ASTExplorer gist](https://astexplorer.net/#/gist/47a4dd99f85cb2fb62907c204bfdd3d8/6e88b258b2d8b31b3ca63c2bc1cc1f7a1194f0e6)

I am not sure if there is something wrong with my codemod, or if this is a bug.

Thanks!

**Comment by jedwards1211** [comment]
Seems like probably a bug in `recast`, or (less likely) `ast-types`.

**Comment by omninonsense** [comment]
@jedwards1211 Do you recommend I close here and reopen in `recast`? I doubt it's an issue with `ast-types`, but I could be wrong.

It's been a while since I've been fiddling with this, but if I remember correctly, it might generally emit `LogicalExpression` wrong (without parens) in more cases than just `OptionalMemberExpression`.

**Comment by jedwards1211** [comment]
Yeah, I did a cursory search in `ast-types` and didn't see any code related to printing in there.  I'd say reopen in `recast`

**Comment by jedwards1211** [comment]
Yup there are definitely plenty of issues related to missing/extraneous parens in `recast`

**Comment by omninonsense** [comment]
I'll close this. I assume it's either been fixed by now and the issue just slipped through the cracks, or there's maybe not enough bandwidth to address it. If someone wants to reopen it, feel free to do so (or ping me, if I have to do it). 🙂

**Comment by rayfrankenstein** [comment]
Here is the solution, I believe.

https://astexplorer.net/#/gist/22a20defe3cd4066a917659a10e82780/2d0f578a80a0c9d437e8bc106777c9e62f4ea15f

The critical line you have to have is:

```memberExpressionChain.object.object.extra = { 'parenthesized': true };```

When doing codemods, type the finished product you want to see at the very end of the process in the upper-left pane of AST-explorer and then look at it's structure/representation in the right pane. Start with the transformed product and work your way backwards through creating the structure that creates it.
