### ISSUE TITLE
enable GitHub Pages for docs

### ISSUE THREAD

**Issue by DanielRuf** [facebook/jscodeshift#340]
Currently the docs are not published.

We can enable the master/docs setting and publish them.
Please also link them in the repository (repo description).

https://danielruf.github.io/jscodeshift/index.html

Reference: https://github.com/facebook/jscodeshift/issues/264

**Comment by huchenme** [comment]
deployed the same: https://jscodeshift.netlify.com/ and it is automatically fetched latest from this repo

**Comment by DanielRuf** [comment]
Hi @huchenme,

thanks but the maintainers and members of this repo have to do this and officially link it.

**Comment by NickHeiner** [comment]
I don't know why this issue was closed, but I would also like to see hosted docs pages.
