### ISSUE TITLE
How to use Collection API in transform file

### ISSUE THREAD

**Issue by DanielRuf** [facebook/jscodeshift#341]
Currently it is not clear if and how we can use the Collection API / class in trandform files.

It seems it is not directly available on `api`.

**Comment by jedwards1211** [comment]
@DanielRuf `api.jscodeshift(code)` returns an instance of `Collection`.  You can also use `api.jscodeshift(paths)` to get a `Collection` of an array of node paths.

**Comment by DanielRuf** [comment]
The docs are not very helpful here ;-)
