### ISSUE TITLE
Please release a patch version

### ISSUE THREAD

**Issue by RShergold** [facebook/jscodeshift#345]
Hey guys. Great work on this excellent tool.

I ran into a fatal error yesterday that was patched a couple of months ago but has still not been released.

The fix is here:
https://github.com/facebook/jscodeshift/commit/298690d1bed85ecb0cb156d158fe19bb9a439803

The error basically occurs when you use stdin to pass in a list of files to be transformed but the stdin ends with an empty new line.

**Comment by jedwards1211** [comment]
Also wanting to get recent fixes in `recast`, and I see that the recast version has already been bumped on master

**Comment by Daniel15** [comment]
@mroch  or @cpojer - Do you know who pushes new versions of jscodeshift these days?

**Comment by jbrown215** [comment]
We ended up releasing 0.7.0 instead of a patch version. The breaking change there is the license change (to MIT). Does that work for you, @RShergold?

**Comment by RShergold** [comment]
Top job. Thanks guys.
