### ISSUE TITLE
How can I traverse the AST in a depth-first-search type way?

### ISSUE THREAD

**Issue by kyldvs** [facebook/jscodeshift#35]
For example I would like to traverse the AST and be able to tell that the second call to `undeclaredCall` is on an undefined variable. Right now I iterate over the entire tree and would see that `undeclaredCall` is defined within a functions' parameters and treat it as "declared" throughout the entire file.

```
function foo(undeclaredCall) {
  undeclaredCall();
}
undeclaredCall();
```

If I'm able to traverse the AST via a DFS with hooks when I enter and exit different scopes, then I can remove `undeclaredCall` from the list of declared variables when I leave the scope of `foo`.

**Comment by fkling** [comment]
Mmh, I wonder if it would make sense to have a method like `forEachScope`, which would iterate over all nodes that create scope, and then you could perform whathever you want to do.

However, I think there are already ways to solve what you want to do. E.g. you can access the path's `scope` to see whether the identifier is declared

```js
    .filter(
        p => !p.scope.declares(p.node.callee.name)
    )
    .replaceWith(
        ({node}) => (node.callee.name += '__FIXME', node)
    )
```

http://felix-kling.de/esprima_ast_explorer/#/nUjPrebRZy

We could think about creating a general `isDeclared` filter for `Identifier`s.
