### ISSUE TITLE
How to add a JSX Comment Block

### ISSUE THREAD

**Issue by cyan33** [facebook/jscodeshift#354]
In JSX if you want to add a block of comment it would look like this:

```
{/* Some comment */}
<Foo />
```

But in astexplorer, the corresponding node to the comment block is:

```
JSXExpressionContainer {
  loc,
  range,
  expression: JSXEmptyExpression {}
}
```
which doesn't have the information of the comment content itself.

If that's the correct structure, it doesn't seem to be able to be built with the builders either?

```
j.jsxExpressionContainer(j.jsxEmptyExpression())
```

I see there's `j.commentLine` but that might not be suitable for JSX. Any pointer is appreciated.

**Comment by cyan33** [comment]
I've got a workaround here:

```
const commentContent = j.jsxEmptyExpression();
commentContent.comments = [j.commentBlock(' bar ', false, true)];

const comment = j.jsxExpressionContainer(commentContent);

const lineBreak = j.jsxText('\n');
element.insertBefore(comment);
element.insertBefore(lineBreak);
```

**Comment by jedwards1211** [comment]
there are a lot of things the builders can't do (and the builders come from `ast-types`; `jscodeshift` just re-exports them). Sometimes you just have to tack properties on after the fact
