### ISSUE TITLE
Couldn't resolve parser "tsx"

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/jscodeshift#357]
Hi there, when I'm trying to use the tsx parser with a codemod I get the error `Error: Couldn't resolve parser "tsx"` any ideas why?

**Comment by mbylstra** [comment]
I had the same problem with the `@storybook/codemod` `storiesof-to-csf.js` transform. I discovered that this error was coming from prettier, which the `storiesof-to-csf.js` transform was using. What I ended up doing was removing the prettier command from the `storiesof-to-csf.js` in my `node_modules` directory, and then just running prettier manually (it was a hack)

Were you also seeing this from `@storybook/codemod`? If so, I don't think it's an issue with jscodeshift, but rather `@storybook/codemod`.

**Comment by lifeiscontent** [comment]
@mbylstra thanks for digging into this, that was exactly my issue! Thank you.

**Comment by mbylstra** [comment]
It turned out that with my hacky fix, although it was running without errors, it wasn't actually transforming the code. I've left an issue here: https://github.com/storybookjs/storybook/issues/9669. This issue should be closed - it's not an issue with jscodeshift.
