### ISSUE TITLE
"babel"/"babylon" parser names are misleading, since babel is used for babel5compat

### ISSUE THREAD

**Issue by jedwards1211** [facebook/jscodeshift#359]

**Comment by NickHeiner** [comment]
Additionally, the help says:

```
      --parser=babel|babylon|flow|ts|tsx  the parser to use for parsing the source files
                                          (default: babel)
```

What's the difference between `babel` and `babylon`?

**Comment by jedwards1211** [comment]
IIRC it seemed to mean an older version of the babel parser but I'm not 100% sure

**Comment by ElonVolo** [comment]
We are planning on cleaning this up at some point. Ideally we'd remove babel5compat (or legacy it) and the babylon settings would be become the new babel.
