### ISSUE TITLE
Feedback: Major Babel upgrade in bugfix version

### ISSUE THREAD

**Issue by tilwinjoy** [facebook/jscodeshift#366]
Hi, Thanks for the great tool.

This isn't a bug, just a suggestion -
Since babel is a"dependency" of this project upgrading it in bugfix versions mean projects using Babel will have to do major upgrade of Babel to get the bugfix release of jscodeshit.
I just spent a couple hours battling an issue to figure out I need to downgrade exactly to 0.6.0 since my project is using Babel 6.

Would be great if such changes are at least marked as a major update!

Thanks! :)

**Comment by gkz** [comment]
I think we've been good about marking any potentially breaking changes as major versions recently.
