### ISSUE TITLE
Add "license" field to package.json

### ISSUE THREAD

**Issue by martinsuchan** [facebook/jscodeshift#384]
The npm page does not show **License** for the npmcodeshift package, see: https://www.npmjs.com/package/jscodeshift
This is causing issues in our internal enterprise package proxy that is blocking any packages without valid whitelisted license type.
I'm not sure if this field in npm repository needs to be filled manually or it's taken from the github source code, but it should be possible to fix it by adding the `"license": "MIT"` field into the package.json file.

Affected version: 0.10.0
Current behavior: npm page does not show any license for this project. package.json does not have "license" field.
Expected behavior: show MIT license on NPM site. Add "license": "MIT" to package.json

![image](https://user-images.githubusercontent.com/3041397/88519184-fef8af00-cff1-11ea-8a37-f8cd6188318f.png)

**Comment by martinsuchan** [comment]
Note the npmjs.com page still does not show the license field for this package.
The maintainer of this package should probably check and fix this most likely one-liner issue:
https://www.npmjs.com/package/jscodeshift

**Comment by gkz** [comment]
It will be fixed the next time a version is published.
