### ISSUE TITLE
Does the unit testing utility work for transforms written in TypeScript?

### ISSUE THREAD

**Issue by eamon-woods** [facebook/jscodeshift#399]
I don't see any options I can set to parse the transform being tested as typescript. I'm working around it by compiling the transform to javascript and testing that, but it'd be nice to be able to skip that step!

**Comment by chimurai** [comment]
I made a full TypeScript example: https://github.com/chimurai/jscodeshift-typescript-example

Hope it helps.

To write the tests in TS; I had to install `ts-jest` & `typescript` and configure `jest` with `jest.config.js` to use `ts-jest`.

**Comment by danielo515** [comment]
You don't need to do any transformation. You just write the test in typescript as normal. The awesome repo that @chimurai posted is a great guidance.
However, there is a problem on the tests: if typing returns any error, the test will fail without any notice.

**Comment by danielo515** [comment]
> To write the tests in TS; I had to install `ts-jest` & `typescript` and configure `jest` with `jest.config.js` to use `ts-jest`.

@woodseamon is asking to write the transformation on TS, not the test themselves. However your answer is still useful

**Comment by manbearwiz** [comment]
Here is another example of a typescript transform, tested with typescript, transforming typescript code, in case it is useful to anyone.

https://github.com/manbearwiz/jscodeshift-ts-satisfies

**Comment by Daniel15** [comment]
Closing this since the question has been answered :)
