### ISSUE TITLE
[pure-component] Parsing error: Identifier `props` has already been declared

### ISSUE THREAD

**Issue by davidnormo** [facebook/jscodeshift#401]
I'm raising this issue for awareness rather than an ask to fix as I spent some time trying to but found issues in recast which need resolving first.

### The Problem
When using the pure-component transform there is an error if a `props` variable has already been declared in the render method:
```javascript
// ...inside MyComponent class
render() {
  const { className, ...props } = this.props
```
The above is transformed into:
```javascript
function MyComponent(props) {
  const { className, ...props } = props // Parsing error
```

### Investigation
- I dug in a bit and managed to resolve this trivial case + other variable declaration types (property, rest, member 
expressions) by renaming them to `props2`
- However when I looked at declarations in a nested block scope those would also be renamed when ideally they should remain unchanged
  ```javascript
  function MyComponent(props) {
    if (true) {
      const props = 'bar' // scoped to the if statement therefore should not be transformed
    }
  ```
- This lead me to look into recast looking up variable bindings by scope and found that recast doesn't support block scoping (https://github.com/benjamn/ast-types/issues/154)
- If this is sorted out then we can fix this issue more comprehensively in pure-component

Let me know if you want me to share my code so far

**Comment by bnjmnt4n** [comment]
This is probably the wrong place to open the issue. Seems like the codemod was from https://github.com/reactjs/react-codemod?

**Comment by davidnormo** [comment]
Ah yep you're right, thanks I'll move it over there
