### ISSUE TITLE
objectProperty builder needs an option to specify if it should use shorthand syntax

### ISSUE THREAD

**Issue by danielo515** [facebook/jscodeshift#403]
Hello.
I was getting nuts about how can you create something as simple as this:

```
({ a }) => a
```

But seems that, with the given api it is not possible, the closer you can get is:

```
({ a: a }) => a
```

Which is correct but it is ridiculous. In order to achieve this you have to create the property and store it on a temp variable, then override the shorthand value and then use it. Seems too much steps for something can be easily specified to the builder function.

**Comment by mobily** [comment]
hey @danielo515! you can actually create a shorthand syntax with jscodeshift, take a look at the example:
```ts
export default function transformer(file, api) {
  const j = api.jscodeshift;

  return j(file.source)
    .find(j.Program)
    .forEach(path => {
      const id = j.identifier('prop')
      const prop = j.property('init', id, id)
      prop.shorthand = true // ⬅️ here!
      const obj = j.objectPattern([
        prop,
      ])
      path.value.body.push(
	j.variableDeclaration('const', [
          j.variableDeclarator(
            j.identifier('test'),
            j.arrowFunctionExpression([obj], j.identifier('prop'))
          )
        ])
      )
    })
    .toSource();
}
```

output:

```
const test = (
 {
  prop
 }
) => prop;
```
AST Explorer: https://astexplorer.net/#/gist/67422b61aa06f0dd723ec06e142c4774/3be1b211215ca68fb288f97a4218b109b2e459c8

**Comment by danielo515** [comment]
Hello @mobily ,I appreciate your answer, but when I say:

> In order to achieve this you have to create the property and store it on a temp variable, then override the shorthand value and then use it. Seems too much steps for something can be easily specified to the builder function.

I am describing exactly what you are proposing, which I consider to not be a satisfactory solution. I want it to be a parameter of the constructor function, not a property you have to inspect the result to deduce and then. annually override it with mutation.

**Comment by ElonVolo** [comment]
While I agree with the annoyance, this behavior is something that has to be changed at the ast-types project level. If they make the change in that library, then jscodeshift can be updated to the new ast-types package that allows for the constructor behavior.

**Comment by soeasyjx** [comment]
I have encountered this problem, I want to create const {h} = require(" packagename "), but the following way, does not achieve the result I want.

**The objectProperty function does not support setting the shorthand property **
#### demo
```js
j.variableDeclaration("const", [
    j.variableDeclarator(
      j.objectPattern([
        j.objectProperty(j.identifier("h"),j.identifier("h"))
      ]),
      j.callExpression(j.identifier("require"), [j.identifier('"packagename"')])
    )
  ]);
```

#### Generated result
```js
const { h:h } =require("packagename")
```

#### Desired result
```js
const { h }=require("packagename")
```
