### ISSUE TITLE
Syntax error on TypeScript's import type syntax

### ISSUE THREAD

**Issue by wdoug** [facebook/jscodeshift#409]
Currently, jscodeshift fails to parse TypeScript 3.8's [`import type` syntax](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) when using the `tsx` parser. A simple demo of this can be seen in [this AST Explorer gist](https://astexplorer.net/#/gist/73bbae5a9084d88eb0f4fa0b4e97f8fe/06b039e8636be4f455afb639fa16d1e9fcd8964f) here.

I believe the issue is caused by the fact that the root version of `@babel/parser` used in this project is [7.2.0](https://github.com/facebook/jscodeshift/blob/48f5d6d6e5e769639b958f1a955c83c68157a5fa/yarn.lock#L236) (this is the [parser used for `tsx`](https://github.com/facebook/jscodeshift/blob/48f5d6d6e5e769639b958f1a955c83c68157a5fa/parser/tsx.js#L12-L27)). The version needed to support TypeScript 3.8 syntax, however, is version [7.9.0](https://babeljs.io/blog/2020/03/16/7.9.0).

**Comment by Daniel15** [comment]
This is fixed in 0.12.0
