### ISSUE TITLE
Unexpected reserved word 'interface' for .tsx files

### ISSUE THREAD

**Issue by rkaveski** [facebook/jscodeshift#421]
When parsing tsx files that contains interfaces, it yells:

<img width="651" alt="Screen Shot 2021-04-19 at 11 59 38 AM" src="https://user-images.githubusercontent.com/1494333/115267083-c90ed400-a106-11eb-8c43-869a8165a83b.png">

<img width="275" alt="Screen Shot 2021-04-19 at 11 59 49 AM" src="https://user-images.githubusercontent.com/1494333/115267088-c90ed400-a106-11eb-9a65-f007fb6c2a72.png">

**Comment by medihack** [comment]
I can confirm this. I get the same error message when trying to transform *.tsx files with interfaces (and nearly all my files have as I use them to type the props).

**Comment by rexxara** [comment]
I have same issue, and i convert **jscodeshift(source).withParser('tsx')** **into jscodeshift.withParser('tsx')(source)** ,then it works.

**Comment by gkz** [comment]
Solution above
