### ISSUE TITLE
Version: 0.12.0. /usr/bin/env: ‘node\r’: No such file or directory 

### ISSUE THREAD

**Issue by gavinxgu** [facebook/jscodeshift#424]
Execute jscodeshift with an error
```
/usr/bin/env: ‘node\r’: No such file or directory 
```

**Comment by machty** [comment]
Ran into this because I tried to install with yarn via `yarn global add jscodeshift`, but [yarn doesn't convert windows line endings](https://github.com/yarnpkg/yarn/issues/5480)

You have to install with npm per the readme (npm converts the line endings):

```
npm install -g jscodeshift
```

**Comment by ZhangYiJiang** [comment]
Another workaround is to call the `jscodeshift` bin in `node_modules` directly, which bypass the shebang at the top of the script - 

``` 
node node_modules/.bin/jscodeshift -t ...
``` 

This is useful if jscodeshift is being called as part of a script, and the package is installed separately or if it's not possible to use a different package manager

**Comment by roddds** [comment]
This is still an issue in 0.13.0.

**Comment by p3k** [comment]
why would i need to rely on a tool that converts windows line endings…? 🤔

**Comment by michaldudak** [comment]
> Another workaround is to call the jscodeshift bin in node_modules directly, which bypass the shebang at the top of the script 

Note that you can't do that if you use Lerna as it creates a bash script in place of the `node_modules/.bin/jscodeshift` JS file.

**Comment by fijiwebdesign** [comment]
You can also reference the `./node_modules/.bin/jscodeshift` directly in an npm script. eg: 

package.js
```
"scripts": {
    "codeshift": "node ./node_modules/.bin/jscodeshift",
    "start": "yarn codeshift -t ./index.js --stdin < ./sample-files.txt",
    "docs": "yarn codeshift --help",
    "test": "jest"
  },
```

**Comment by sibelius** [comment]
any workaround on m1?

**Comment by jediswear** [comment]
> any workaround on m1?

works on m1
> Another workaround is to call the `jscodeshift` bin in `node_modules` directly, which bypass the shebang at the top of the script -
> 
> ```
> node node_modules/.bin/jscodeshift -t ...
> ```
> 
> This is useful if jscodeshift is being called as part of a script, and the package is installed separately or if it's not possible to use a different package manager

**Comment by sibelius** [comment]
node node_modules/.bin/jscodeshift -t ...

is not working for me

**Comment by pvinis** [comment]
it gives the same error even with `npx jscodeshift`.

**Comment by Daniel15** [comment]
This is strange... I'm not sure how Windows line endings ended up in the file.

**Comment by dreyks** [comment]
I think the issue is not in the windows line-ending per se, I guess node is smart enough to work with it. what's not smart enough is bash - the `\r` in the shebang string which turns it into `#!/usr/bin/env node\r`

**Comment by sibelius** [comment]
here more on this https://techtalkbook.com/env-noder-no-such-file-or-directory/

**Comment by sibelius** [comment]
anybody can give a try here https://github.com/facebook/jscodeshift/pull/549?
