### ISSUE TITLE
Flow maybe types cause `Transformation error`

### ISSUE THREAD

**Issue by jennykortina** [facebook/jscodeshift#458]
I am trying to run the material UI upgrade script `npx @mui/codemod v5.0.0/preset-safe <path>` which uses jcodeshift.  Our project is react with flow.  Whenever the script gets to a flow maybe type eg `days: ?number` it throws a `Transformation error (Unexpected token)`  

I have tried using the ` --no-babel --parser=flow` flags but still get the same error.  Is there a flag I am missing or is this a known issue? Thanks so much in advance!

**Comment by ElonVolo** [comment]
Yo maintainer, might wanna close this one.

**Comment by mroch** [comment]
ThAnks @ElonVolo!
