### ISSUE TITLE
Possible to flatten?

### ISSUE THREAD

**Issue by aaronjensen** [facebook/jscodeshift#46]
Sometimes I want to flatten a collection. For example, I may get a CallExpression's arguments and want to act on each of them. Is this easy/possible now, or could we have a flatMap?

**Comment by fkling** [comment]
`.map` should already work like `flatMap`: https://github.com/facebook/jscodeshift/blob/master/src/Collection.js#L76-L89

**Comment by aaronjensen** [comment]
This is what I'm referring to:

http://felix-kling.de/esprima_ast_explorer/#/AC45LUt7N6/1

The log should print 4

**Comment by fkling** [comment]
Ah. `path.get('arguments')` doesn't return an array, it returns a `NodePath` that contains an array. To return an array of paths you would have to do 

```js
path => path.get('arguments').map(p => p)
```

http://astexplorer.net/#/AC45LUt7N6/2

Not super elegant, but it works ;)

**Comment by aaronjensen** [comment]
Sweet, works for me, thanks!
