### ISSUE TITLE
How to get body of a function?

### ISSUE THREAD

**Issue by ivanjeremic** [facebook/jscodeshift#468]
I found jscodeshift and read it has some nice jQuery like APIs, I imagined I could do things like 
```
j("function foo() {console.log(''fnBody')};").body
```
gives me fn body as string.
`>> console.log(''fnBody')`

Is there some API in jscodeshift for that?

Thanks

**Comment by mobily** [comment]
as far as I know, there's no API like this, the only way to achieve what you want is using the `find` method to get collection elements (`FunctionDeclaration` in this specific case), and once you have them, you may want to transform them to get a function body, for instance:

codemod:

```js
export default function transformer(file, api) {
  const j = api.jscodeshift;
  
  return j(file.source)
    .find(j.FunctionDeclaration)
    .filter(p => p.value.id.name === 'foo')
    .replaceWith(p => {
      return p.value.body.body
    })
    .toSource()
}

```

input:

```js
function foo() {console.log('fnFooBody')};
function bar() {console.log('fnBarBody')};
```

output:

```js
console.log('fnFooBody')
function bar() {console.log('fnBarBody')}
```

https://astexplorer.net/#/gist/7949506fd5453d2a023c46f3c714d185/14ab925d1bca17750b96631cada5c2fb8ccb3f35

**Comment by ElonVolo** [comment]
That's my approach as well.
