### ISSUE TITLE
Programmatic Usage

### ISSUE THREAD

**Issue by thejameskyle** [facebook/jscodeshift#47]
The CLI works great, but it'd be nice to have a friendly API for using jscodeshift within a node script (I'm attempting to use it within yeoman).

`Runner.run` works, but there's no callback, stream, or promise returned so you can't tell when it's finished. Maybe that's all that needs to be changed.

**Comment by cpojer** [comment]
What kind of programmatic usage are you looking for? You can `require('jscodeshift')` and use its API like you would in a transform. We haven't made an effort to split out the runner from jscodeshift but you can always use it by calling exec.

**Comment by thejameskyle** [comment]
Yeah, I was trying to do this:

```js
var jscodeshift = require('jscodeshift');
jscodeshift.run(...);
```

However, `run` does stuff asynchronously without returning the promise here: https://github.com/facebook/jscodeshift/blob/master/src/Runner.js#L96
