### ISSUE TITLE
Critical: Need to restrict colors.js dependency

### ISSUE THREAD

**Issue by bodograumann** [facebook/jscodeshift#474]
You have included `colors@^1.1.2` as dependency, which would install version `1.4.1`. This dependency contains an intentional DoS.
Please pin to version `1.4.0`.

For background: https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

**Comment by bodograumann** [comment]
Seems there are already some pull-requests. Nice :-)

**Comment by mroch** [comment]
i merged #473 to use chalk instead. thanks @bodograumann @yedidyak @imnotjames for your quick response to this issue!
