### ISSUE TITLE
Add support for Flow's `IndexedAccessType`

### ISSUE THREAD

**Issue by pascalduez** [facebook/jscodeshift#478]
Currently `jscodeshit@0.13.1` choke on Flow's indexed access types.

> Error: did not recognize object of type "IndexedAccessType"

It should be "just" a matter of updating `recast`, which comes with `ast-types`. 
Support for `IndexedAccessType` was added as of `ast-types@0.15.0`.

EDIT: as of today, both `recast@0.21` and `ast-types@0.15` are not published on the `latest` tag, but `next`.

/cc @benjamn

**Comment by pascalduez** [comment]
Thanks @gkz for the update on master.

I tried with this `jscodeshift` version (git), and the `IndexedAccessType` errors are gone.

But now it's choking on:  
`did not recognize object of type "QualifiedTypeofIdentifier"`
`did not recognize object of type "PropertyDefinition"`
Which is weird since they are not new type syntax. 
:woman_shrugging:

**Comment by gkz** [comment]
Thanks for the report. When people make changes to our AST output, they sometimes don't update the `ast-types` as well. In this case, using an older version of `flow-parser` will make this work for you. Since `jscodeshift` specifies `flow-parser` `0.*`, you can resolve it to whatever. We're currently using `flow-parser` `0.152` for jscodeshift and it works for us, a later version could also probably work.

**Comment by pascalduez** [comment]
For reference to other potential FLow users:

```json
"resolutions": {
    "**/ast-types": "npm:@gkz/ast-types",
    "**/flow-parser": "0.152"
  }
```
Downside, `yarn link` doesn't works for CLIs...

**Comment by gkz** [comment]
Actual `ast-types` package now includes support for `IndexedAccessTypes`

**Comment by pascalduez** [comment]
I tried removing the overrides and all the errors are back. So I guess the whole chain transitive is not up to date or fixed yet.

**Comment by seansfkelley** [comment]
Apologies for the tangent on a closed issue, but this is currently the highest relevant search result for `QualifiedTypeofIdentifier` and `PropertyDefinition` errors. If you encounter those, you can install the `ast-types` fork defining `PropertyDefinition` from https://github.com/benjamn/ast-types/pull/727. (There's no PR I see for `QualifiedTypeofIdentifier`, and I don't actually know or care what these node types look like so I haven't offered my hacky fork as a PR.)
