### ISSUE TITLE
Bake in ability to preprocess the transform script

### ISSUE THREAD

**Issue by wincent** [facebook/jscodeshift#5]
The motivating use case here is the ability to transform the transform script with a tool like Babel (or other) prior to use.

Just say you're working on a large project where you don't control the build process and so you can't integrate your transform scripts with it.

Or alternatively, say you're wanting to run a transform script that comes from somewhere else (eg. another repo checked out somewhere else on the filesystem), and again you can't transparently pre-build the transform.

Current workaround is to make a simple wrapper that does the transform first.

Question is, is it outside the scope of jscodeshift to make it easy to plug-in some preprocessing step for the transform prior to using it? Possible questions:

- should `jscodeshift` accept a transform script via standard input? (in which case you could do something like `babel myTransform.js | jscodeshift ....`)
- should we expose a `--preprocess` option that allows the user to specify an executable to pre-process the transform before running it?
- should we expose another mechanism to inject a JS module that does the preprocessing?
- what would the implications of this be for preprocessing the other files (ie. the ones that the transform operates on?)

**Comment by wincent** [comment]
Like the label says, putting this here for discussion. I am not even sure this is a good idea yet.

**Comment by cpojer** [comment]
I think I'd vote for option 1 unless we are certain babel is becoming a standard. But at the same time it means jscodeshift will forever depend on babel, even after ES6 is fully implemented in v8/node, assuming that babel will always support future language features.

**Comment by wincent** [comment]
Yeah, I definitely don't want to add another dependency; I just want to make it possible to integrate with a preprocessing step (not necessarily Babel) without having to build a wrapper.

**Comment by cpojer** [comment]
I guess we are certain now that babel became a standard :)

**Comment by pieterv** [comment]
This is awesome, thank you!
