### ISSUE TITLE
Class decorators are dropped

### ISSUE THREAD

**Issue by ide** [facebook/jscodeshift#50]
After running [this transform](https://gist.github.com/ide/f3266c3915b0e45dac78) jscodeshift ate up all my class decorators e.g.:

```js
@connect(data => getDataProps(data))
class Screen extends React.Component {
}
```

became

```js
class Screen extends React.Component {
}
```

**Comment by cpojer** [comment]
This should be easy to add to recast!

Just add your types to the giant switch statement: https://github.com/benjamn/recast/blob/master/lib/printer.js#L1137 – decorators should be easy to print :)
