### ISSUE TITLE
Ignoring "empty" files

### ISSUE THREAD

**Issue by caridy** [facebook/jscodeshift#54]
Empty files, or files with no code (empty, or just breakline) will throw errors while transforming...

```
ERR  /javascript/foo.js Transformation error
TypeError: Cannot read property 'line' of null
    at Object.exports.fixFaultyLocations (/node_modules/recast/lib/util.js:142:22)
    at TreeCopier.TCp.copy (/node_modules/recast/lib/parser.js:98:10)
    at TreeCopier.TCp.copy (/node_modules/recast/lib/parser.js:135:30)
    at Object.parse (/repo/aura-codemod/node_modules/recast/lib/parser.js:78:34)
    at fromSource (/repo/aura-codemod/node_modules/jscodeshift/dist/core.js:72:25)
```

I suspect that it is jscodeshift the one reading from disk, and just passing the empty content to recast, that's why I'm opening the issue in this repo.

_Note: why are those files empty is not important, but should not be an indication of error, at the end of the day, they are valid javascript source._

**Comment by fkling** [comment]
> I suspect that it is jscodeshift the one reading from disk

True

> and just passing the empty content to recast

That happens in the transform function itself, i.e. user code. I guess we could add an option `--ignore-empty` and not invoke the transform for these files. But if you know that you may have empty files, you could also just do

```js
if (source.trim() === '') {
  return;
}
```

in the transform.

Thoughts?

I still think this is something that should be fixed in recast.

**Comment by caridy** [comment]
Probably, considering that an extra guarding around `loc.start.line` and `loc.end.line` is probably enough (https://github.com/benjamn/recast/blob/master/lib/util.js#L141-L150), @benjamn are you ok with that? any implications that we are not taking into consideration? I can submit a PR for recast.

**Comment by fkling** [comment]
This is probably solved with https://github.com/benjamn/recast/commit/34b660650d23f05f2bdcc36f31c6851c7be60123 .

**Comment by caridy** [comment]
:clap:
