### ISSUE TITLE
can I access docs online?

### ISSUE THREAD

**Issue by sibelius** [facebook/jscodeshift#545]

**Comment by Daniel15** [comment]
There's no docs online at the moment, but maybe we should publish the autogenerated API docs to GitHub Pages...

**Comment by roddds** [comment]
There's this, but it's not much better than reading the source:

https://npmdoc.github.io/node-npmdoc-jscodeshift/build/apidoc.html

**Comment by sibelius** [comment]
We should migrate docs do docusuarus

**Comment by olrtg** [comment]
Hey @sibelius! I'm currently learning the tool to do some migrations at work and it's been quite hard to do things with it. I would like to help with the docs and maybe put some specific examples of how to use the API with real-world examples. Would need some mentoring though with the API from time to time. How can we move forward with this?

**Comment by ElonVolo** [comment]
I'm one of the jscodeshift maintainers and even I end up referring back to tutorials if I haven't written a codemod in months. Doing anything with ast-types (a separate project that's the real business end up jscodeshift) is a bear but that is the library you have to learn to make maximal use of jscodeshift.

At this, my go-to is starting to be ChatGPT. Most of the code that gets generated has some mistakes, but it largely gets the ast-types constructor calls mostly right.

**Comment by olrtg** [comment]
Hi @ElonVolo! thanks for replying. That's helpful! I probably need more AI in my life haha

Aside from that, I guess you're not interested in building a docs website, am I correct? 🤔

**Comment by mohab-sameh** [comment]
@Daniel15 please assign his to me. I'll revamp docs (probably on Mintlify). I'll incrementally move things from wiki, readme, and other relevant resources to the online docs until it's complete.

The current docs structure I have in mind is as follows:
- overview
    - includes general info about `jscodeshift`
        - what it is
        - how it works
            - run
                - cli
            - build
                - find
                - transform
- build
    - api reference
- run
    - cli reference
- guides (TBD)
    - building codemod guides
    - etc.

Please let me know if you have some suggestions or requests on how the docs should look like.

**Comment by trivikr** [comment]
Can this be closed since docs were added in https://github.com/facebook/jscodeshift/pull/592, and deployed on https://jscodeshift.com/?

cc @Daniel15 @mohab-sameh
