### ISSUE TITLE
Allow passing options to recast

### ISSUE THREAD

**Issue by jamischarles** [facebook/jscodeshift#55]
I'm running into this issue https://github.com/benjamn/recast/issues/171 and would like to pass options to override the quote settings. 

If you're onboard, I can gladly issue a PR.

Thoughts?

**Comment by jamischarles** [comment]
Appears to be related to https://github.com/facebook/jscodeshift/issues/4

**Comment by jamischarles** [comment]
Ah, just saw that this is possible. This would be great to add to the readme :)

```js
.toSource({quote:'single'})
```

**Comment by wincent** [comment]
> This would be great to add to the readme

Would you like to have a crack at that in a PR?

**Comment by fkling** [comment]
I assume this can be closed then?

**Comment by jamischarles** [comment]
Yep. Thx!

**Comment by NefeliSylvia** [comment]
Hi everyone! how can i get the source map? i assumed i need write something like

```
var root = jscodeshiftAPI(code,{sourceFileName: fileName});
//write transformations
result = root.toSource({sourceMapName: "map.json"});

```
but result doesn't have the .map property
