### ISSUE TITLE
Cannot find module `lodash`

### ISSUE THREAD

**Issue by SorsOps** [facebook/jscodeshift#550]
See the following for context https://github.com/backstage/backstage/issues/16839 . It seems there is a require to lodash in the dist of jscodeshift, however jscodeshift does not have lodash listed as a dependency

**Comment by Daniel15** [comment]
Lodash hasn't been required for two years now (removed in #432). Please update your jscodeshift version to 0.13.0 or higher.

https://github.com/search?q=repo%3Afacebook%2Fjscodeshift%20lodash&type=code
