### ISSUE TITLE
Easiest way to insert a comment at the beginning of a file?

### ISSUE THREAD

**Issue by brexmatt** [facebook/jscodeshift#569]

**Comment by ayushsgithub** [comment]
# This is a comment at the beginning of a Python file



/* This is a CSS comment at the beginning of the file */

# This is a comment at the beginning of a Bash script



# Markdown file with an HTML-style comment at the beginning

**Comment by ayushsgithub** [comment]
`# This is a comment at the beginning of a Python file



/* This is a CSS comment at the beginning of the file */

# This is a comment at the beginning of a Bash script



# Markdown file with an HTML-style comment at the beginning


`

**Comment by ayushsgithub** [comment]
![Screenshot 2023-09-22 122151](https://github.com/facebook/jscodeshift/assets/120788538/63974051-3d44-4875-a177-cd3c72cbca88)

The first comment is in Python.
The second comment is in HTML.
The third comment is in CSS.
The fourth comment is in Bash.
The fifth comment is another HTML comment.
The last comment is in Markdown (using an HTML-style comment).

**Comment by ElonVolo** [comment]
Putting a comment line at the beginning of the file is probably one of the few cases where I'd just do straight-up concatenation over generating code.

Just open file, read contents into string, and prepend the line to the file's string contents.

I also tried ChatGPT and it generated something convincing.

**Comment by brexmatt** [comment]
> Putting a comment line at the beginning of the file is probably one of the few cases where I'd just do straight-up concatenation over generating code.
> 
> Just open file, read contents into string, and prepend the line to the file's string contents.
> 
> I also tried ChatGPT and it generated something convincing.

thanks
