### ISSUE TITLE
Last npm release (0.15) is ~6 months old

### ISSUE THREAD

**Issue by HughCrail** [facebook/jscodeshift#577]
I would love to use a version of jscodeshift which uses a newer version of `babel/parser` - as the code base I wish to transform makes use of newer JS features.

I see that the main branch has a dependency on a much newer version of babel - Is it possible to release a new version to npm?

Thank you

**Comment by Daniel15** [comment]
Sure, I'll push it this week. I want to see if we can automate pushing development builds too.

**Comment by Daniel15** [comment]
0.15.1 has been published. Please allow 20-30 minutes for npm to update their caches.
