### ISSUE TITLE
WSL2 - Can't install project with jscodeshift in dependencies

### ISSUE THREAD

**Issue by okwergot** [facebook/jscodeshift#579]
Hello!
my project have dependency to package

jscodeshift@^0.14.0:
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/jscodeshift/-/jscodeshift-0.14.0.tgz#7542e6715d6d2e8bde0b4e883f0ccea358b46881"
  integrity sha512-7eCC1knD7A==
  dependencies:
    ....
    flow-parser "0.*"

when i try install packages on wsl2 or win10 , yarn throw error

➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0082: │ flow-parser@npm:0.*: No candidates found
➤ YN0000: └ Completed in 17s 493ms
➤ YN0000: · Failed with errors in 17s 508ms

**Comment by ElonVolo** [comment]
Here's my standard troubleshooting

1. Delete package-lock.json or yarn.lock
2. Delete node_modules/ directory
3. Upgrade to latest jscodeshift
4. run npm install or yarn install
5. If still not working, download ncu and update all packages and repeat steps 1, 2, and 4
6. Completely deinstall node from your computer and reinstall it and repeat steps 1-5.
7. If it still doesn't work by this point, write a stern e-mail to Satya Nadella asking him to take some responsibility for him company's stack.
