### ISSUE TITLE
Enable parsing of `accessor` keyword

### ISSUE THREAD

**Issue by RhodeHummel** [facebook/jscodeshift#580]
It looks like jscodeshift does not currently support the accessor keyword that was added typescript in 3.9. Can we please add support for this. Thank you.

https://github.com/microsoft/TypeScript/pull/49705
https://github.com/tc39/proposal-decorators

**Comment by ElonVolo** [comment]
Would you be able to add the content you were trying to transform, the transformation script you wrote, the command you ran to transform it, and the expected output, to the issue?

**Comment by Daniel15** [comment]
I think this will need upstream changes (recast)

**Comment by RhodeHummel** [comment]
@ElonVolo Here is a simple case. Basically, I just want it to run with out any errors. Hope this is enough information for you.

```ts
// test-file.ts
export class Test {
    public accessor myValue = 10;
}
```

```ts
// test-transform.ts
import { FileInfo, API, Options } from 'jscodeshift';

module.exports = function (file: FileInfo, { j }: API, _options: Options) {
    const root = j(file.source);

    // Do nothing just output the file again
    return root.toSource();
};
```

**Comment by ElonVolo** [comment]
I'm running the tranform and file code you submitted and I'm not getting any errors. Nothing's being transformed, which is expected as no modifications have been made.

Are you getting some different result on your end?

**Comment by ElonVolo** [comment]
> I think this will need upstream changes (recast and/or ast-types)

I looked at the recast code and there does seem to be some support for Typescript's **accessor** keyword.

**Comment by RhodeHummel** [comment]
@ElonVolo I definitely get an error. There is no error message, it just prints out results 1 error instead of 1 unmodified. I have created an isolated test case and included it here.

To see the error, run `npx ts-node test.ts`

[jscodeshift-error.zip](https://github.com/facebook/jscodeshift/files/13906755/jscodeshift-error.zip)
