### ISSUE TITLE
Replace `chalk` dependency with a lighter alternative

### ISSUE THREAD

**Issue by trivikr** [facebook/jscodeshift#600]
### Is your feature request related to a problem? Please describe.

Recently, the [Ecosystem Performance](https://e18e.dev/) was formed to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

On the e18e cleanup channel on Discord, multiple solutions are being discussed. One of them is to replace `chalk` with `picocolors`. I see that jscodeshift uses `chalk` https://github.com/facebook/jscodeshift/blob/0994ad8361a37e6f7c4f167c3ddfc73ebb2083f3/package.json#L37

### Describe the solution you'd like
Replace `chalk` with a lighter alternative, like `picocolors`.

**Comment by trivikr** [comment]
I created a similar feature request with jscodeshift devDependencies which uses chalk:
* jest https://github.com/jestjs/jest/issues/15189
* eslint https://github.com/eslint/eslint/issues/18686

Babel already replaced `chalk` with `picocolors` in https://github.com/babel/babel/pull/16359

**Comment by Daniel15** [comment]
What does "light" mean in this case? Could you please share the metrics being used?

**Comment by trivikr** [comment]
> What does "lighter" mean in this case? Could you please share the metrics being used?

It usually means an alternative with a smaller size (install/publish/bundle).

The dependency `chalk@4.x` which jscodeshift uses has [~33 kB publish size and ~105 kB install size](https://packagephobia.com/result?p=chalk@4.0.0).

<details>
<summary>Screenshot</summary>

<img width="767" alt="Screenshot 2024-07-15 at 8 32 55 AM" src="https://github.com/user-attachments/assets/8351a140-67d6-4414-b8a8-27dd900b4de9">

</details>

On other hand, picocolors has [5.03 kB install/publish size](https://packagephobia.com/result?p=picocolors)

<details>
<summary>Screenshot</summary>

<img width="588" alt="Screenshot 2024-07-15 at 8 34 10 AM" src="https://github.com/user-attachments/assets/4bad253b-2eb1-4c7f-b067-3f2e1142d554">

</details>

The lighter alternatives sometimes come with performance benefits too.
The picocolors benchmarks state it's 2X faster than chalk in their README.
