### ISSUE TITLE
Replacement of nodes contained in others nodes already replaced

### ISSUE THREAD

**Issue by igncp** [facebook/jscodeshift#63]
Hi,

I think there might be something not working well, maybe in jscodeshift or in recast, but not completely sure yet. The case is when you try to replace a node A which is contained in another B. B has already been replaced. It uses strings as replacements in A and B. This is the example (this transformer is intended to add a trailing comma at the end of every property in object expressions): http://astexplorer.net/#/fU8E4pJxdx/4

The expected value would be:

```javascript
var x = {
	b: function(){
    	var z = {
          b: 3,
          c: 1,
        };
    },
  	d: 2,
};

var y = {
	i: 2,
};
```
 
But as you can see, `c: 1` does not contain a comma at the end in the example. I have tried it locally and the same happens. Doing some logging, the transformer passes through the `replaceWith` function related with the 

```javascript
{
  b: 3,
  c: 1
}
```

after the replacement of the container ObjectExpression, and everything seems to be working fine, so it should be replacing it but the final result does not contain it. Any ideas? Am I missing something?

**Comment by fkling** [comment]
jscodeshift (and recast and ast-types) works on AST nodes. Even though it seems to be possible to return source code from `replaceWith`, the code will be converted to an AST again. ASTs are *abstract* (*Abstract* Syntax Tree), they don't contain any information about formatting (and the placement of the `,` is part of the formatting).

Formatting is handled by the *printer* and [recast actually has an option to print trailing commas](https://github.com/benjamn/recast/blob/52a7ec3eaaa37e78436841ed8afc948033a86252/lib/options.js#L66).

jscodeshift is not a source code formatter and as such is probably not the right tool for what you are trying to do. [eslint](http://eslint.org/docs/user-guide/command-line-interface) with autofixing might be better suited.

**Comment by igncp** [comment]
So that was it! I get that it was a wrong transformer because it took into account the formatting, and it shouldn't as the AST doesn't handle that. eslint works great but I want to stick to jscodesift to keep learning about it. I'll take a look into the printer but I understand that jscodeshift is for changing the AST and not the formatting of the code, thanks!
