### ISSUE TITLE
How to find root member expression?

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/jscodeshift#65]
How can I find usages of `_.chain(x).y().z()…`, like so:

```
var foo = [];
var x = _.chain(foo)
    .map(function () { return x; })
    .filter(function () { return x; })
    .value();
```

where I don't know how many methods will be called?

The closest I've come is to finding the `MemberExpression` of `_.chain`, but I need to find the entire expression that is being assigned to `x`. Furthermore, I want to match usages of `_.chain` in other contexts, such as `CallExpression`s:

```
foo(_.chain([]).map(x => x));
```

My goal is to build a list of all the methods being called on `_.chain(foo)`, i.e. `map`, `filter`, `value`.

**Comment by OliverJAsh** [comment]
This was the closest I could get:

``` js
    var chainAsts = ast
        .find(j.CallExpression, node => (
            node.callee.object
              && node.callee.object.name === '_'
              && node.callee.property.name === 'chain'
        ))
        .map(nodePath => {
            var currentNodePath = nodePath.parentPath;
            console.log(currentNodePath);
            while (currentNodePath.parentPath.value.type !== 'VariableDeclarator'
                   && currentNodePath.parentPath.value.type !== 'ExpressionStatement'
                   && currentNodePath.parentPath.value.type !== 'ReturnStatement') {
                currentNodePath = currentNodePath.parentPath;
            }
            return currentNodePath;
        });
```

But it's extremely flaky and doesn't work in all conditions.

**Comment by chrisdarroch** [comment]
If what you're aiming to do is just list the functions chained on the calls, you can take advantage of a couple of properties of the AST:

* The `_.chain` will always be the most deeply nested `MemberExpression` of any `CallExpression`
* a `CallExpression` that doesn't have a nested `MemberExpression` as a callee cannot be a chaining of underscore methods
* Finding all `CallExpression` nodes will return you everything from the first call in the AST (i.e., to `.value()`) all the way down to the `_.chain` call itself.

Given those things, you can list out the methods being chained by doing something like the following:

```js
  const j = jscodeshift;

  let callsWithChains = 
    j(file.source)
    .find(j.CallExpression)
    .filter(p => {
      let found = false;
      let nestedCalls = j(p).find(j.CallExpression);
      nestedCalls.forEach(nc => {
        found = found || isChainCall(nc.value);
      });
      return found;
    });

  let justTheChains = 
    callsWithChains
    .filter(p => {
      let n = p.value;
      return n.callee.type === 'MemberExpression';
    });

  let results = [];
  justTheChains.forEach(p => {
    let n = p.value;
    let methodName = n.callee.property.name;
    let src = j(n).toSource();
    results.push( "['" + methodName + "'," + src +"]")
  });
  
  return results.join("\n\n");

```

I've put an example up on AST explorer: http://astexplorer.net/#/Jtibj3uEoH

Hope that helps :)
