### ISSUE TITLE
Re-use old AST

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/jscodeshift#66]
When transforming the AST, it would be useful to re-use part of the old AST so I don't have to manually reconstruct all nodes nested in the part I'm transforming:

``` js
module.exports = function(file, api) {
  const j = api.jscodeshift;
  const {expression, statement, statements} = j.template;

  return j(file.source)
    .find(j.Identifier)
    .replaceWith(
      p => j.memberExpression(j.identifier('foo'), p)
    )
    .toSource();
};

```

Is this possible?

**Comment by fkling** [comment]
Of course. The builders don't care where the node comes from. But in your example, `p` is a `NodePath`.  If you want to access the contained AST node, you need to use `p.node` or `p.value`.

**Comment by OliverJAsh** [comment]
Thanks!
