### ISSUE TITLE
Copy indentation and comments across to new nodes

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/jscodeshift#67]
I am regenerating nodes but I would like to retain indentation and comments for those nodes, i.e.

``` js
foo
  .baz // bob
  .bar
```

If I process this:

``` js
j(file.source)
    .find(j.MemberExpression)
    .replaceWith(
      p => j.memberExpression(p.node.object, p.node.property)
    )
    .toSource()
```

I get:

``` js
foo.baz.bar
```

As in http://astexplorer.net/#/RKmXYV9kFT/1

Is there a way to retain indentation and comments? Keeping in mind that sometimes I might need to rename things.

**Comment by fkling** [comment]
cc @benjamn regarding indentation (recast does that, not jscodeshift)

Regarding comments, you could simply copy over the comment information from the old node to the new node. However, maybe this could be even automated.

**Comment by benjamn** [comment]
The indentation is not going to be preserved unless all you're doing is changing the `.name` properties of the identifiers. The rule of thumb is that new nodes get printed by the pretty-printer, and the pretty-printer has no way of understanding what style you're aiming for, so it just does something reasonable and predictable.

In this case it's tempting to say the replacement nodes are "similar enough" to the original nodes that some of the original whitespace could be borrowed, but I haven't been able to formalize that notion of similarity, and I would challenge you to imagine an inference algorithm that decides whether whitespace in the source code should end up as whitespace in the output. What if the line gets longer (or shorter) and needs to be broken in different places? What if there are new comments? It gets really complicated, and it's important to appreciate the difference between code that you would have written by hand and code that is slightly different from your personal style, but correct and readable in all possible scenarios.

As for the comments, you can try moving the `ast.program.body[0].expression.object.comments` property to the new `MemberExpression` node. It's possible that the `.replace` method could even do this for you. However, I have to warn you that trailing comments are tricky, especially when they occur in the middle of larger nodes (see https://github.com/benjamn/recast/issues/191).

What I can guarantee you is that the transplanted comments will end up somewhere, as long as they're still attached to the AST. My guess is that you'll get either
```js
// bob
foo.baz.bar
```
or
```js
foo.baz.bar // bob
```

**Comment by benjamn** [comment]
I realize that was sort of rambling, so let me be clear: I think it is probably a good idea (and easy) for the `.replaceWith` method to copy the `.comments` of the old node onto the new node, whenever the old node has a `.comments` property.
