### ISSUE TITLE
Removing an Import also removes the class decorators.

### ISSUE THREAD

**Issue by tmbtech** [facebook/jscodeshift#70]
Hi, 

I'm trying to remove an import statment, but everytime I attempt to remove it, the decorators also get removed. Is there another way to handle this?

http://felix-kling.de/esprima_ast_explorer/#/mgA15bmVhm/3
I'm using the `babel-core` parser.

**Comment by fkling** [comment]
Mmh, that's weird. However, your log shows that the the decorators are still there, so maybe it's just a printing issue? cc @benjamn

**Comment by tmbtech** [comment]
@benjamn @fkling ,

I think it is, if I add a decorator, they all come back.
http://felix-kling.de/esprima_ast_explorer/#/jRtVOVoKPt/2

**Comment by fkling** [comment]
There are a couple of issues open related to decorators:

https://github.com/benjamn/recast/issues/243
https://github.com/benjamn/recast/issues/241

I guess this is related. Might be worth opening a PR over there.

**Comment by fkling** [comment]
Mmh, even after upgrading recast to v0.10.41, this continues to be a problem, @benjamn.

**Comment by benjamn** [comment]
Noted, I'll take another look at this.

**Comment by benjamn** [comment]
Try [`recast@0.10.42`](https://github.com/benjamn/recast/releases/tag/v0.10.42)?

**Comment by fkling** [comment]
@benjamn: Works now! Thanks a lot!

Reinstalling jscodeshift should solve this. I might push a new versions with updated dependency versions though.
