### ISSUE TITLE
Is there a way to determine if any changes were made?

### ISSUE THREAD

**Issue by necccc** [facebook/jscodeshift#72]
Right before `toSource()` I might want to determine if any changes were done in the currently processed file. Is there a way for it?

**Comment by joshblack** [comment]
A common way from the reference examples is to check the `.size()` of a resulting collection that they modify. For example, when converting React classes the pattern used is:

```js
// https://github.com/reactjs/react-codemod/blob/master/transforms/class.js#L509-L516
const didTransform = (
  apply(ReactUtils.findReactCreateClass(root), 'var')
    .size() +
  apply(ReactUtils.findReactCreateClassModuleExports(root), 'moduleExports')
    .size() +
  apply(ReactUtils.findReactCreateClassExportDefault(root), 'exportDefault')
    .size()
) > 0;

if (didTransform) {
  return root.toSource(printOptions);
}
```

Where a developer will look for a type of node, and apply the transformations that are appropriate. The result is a Collection in this case, and so verifying that the size of these collections is non-zero is a good approximation for if a change occurs. 

If you want more granular diff'ing, might be worthwhile to hold on to the structure that you're looking to transform before applying a transform and then comparing the two different versions of your node before returning `toSource`

**Comment by fkling** [comment]
There isn't a canonical way to do this, and there is no simple way to determine whether the AST changed, except keeping a copy of the original tree and walk both trees.

If your code performs the mutation, the simplest solution is to have a variable to track the state and update it as necessary.

If you are using some third party function that performs the mutation, then I'm not sure what the best way would be (besides tree walking).
