### ISSUE TITLE
Remove trailing semicolon from ObjectExpression in static ClassProperty

### ISSUE THREAD

**Issue by joshblack** [facebook/jscodeshift#74]
Was looking into how to add a ClassProperty inside of a ClassDeclaration, specifically a static one containing an ObjectExpression. For this, my builder looks similar to:

```js
.replaceWith(
  (p) => j.classBody([
           j.classProperty(
             j.identifier('propTypes'), 
             j.objectExpression(propTypes), 
             null, 
             true
           ),
           ...p.node.body
         ]));
```

However, a trailing semicolon is added in the transformation, so instead of:

```js
class Foo {
  static foo = {
    bar: 'baz'
  }
}
```

The transformation looks like:

```js
class Foo {
  static foo = {
    bar: 'baz'
  };
}
```

Is there any way to exclude this semicolon after the class property definition?

Relevant workspace: http://astexplorer.net/#/5j2WGLMyTF/1

**Comment by fkling** [comment]
Why do you want to remove it? If any, it has something to do with recast's printer, not jscodeshift.

**Comment by joshblack** [comment]
Good point, there's no real reason for removal other than consistency with the code base I'm updating old code for. And totally right about the recast printer, I'll try looking there. Thanks!
