### ISSUE TITLE
Create alias for nodePath.replace() to easily remove/delete a node

### ISSUE THREAD

**Issue by kyldvs** [facebook/jscodeshift#78]
I frequently finding myself wanting to do:

```
path.remove();
```

In order to remove a certain path. Right now I've been doing:

```
j(path).remove();
```

In order to remove things. I've recently found out that

```
path.replace();
``` 

also removes a path, can we create an alias to `path.replace()` at `path.remove()` ?

**Comment by fkling** [comment]
I don't really want to monkey patch recast...

**Comment by kyldvs** [comment]
Ah, I guess this should be an issue on recast then.
