### ISSUE TITLE
RFC: `-t` for remote codemods

### ISSUE THREAD

**Issue by iamdustan** [facebook/jscodeshift#94]
Currently, community-specific codemods are appearing inside specific repos without much shareability and the ergonomics to apply them require quite a bit of manual effort (especially for a tool based around removing manual effort).

Allowing `-t` to accept remote codemods would enable a generic way to build a hosted service and share codemods.

**Comment by fkling** [comment]
:+1:  I was wondering how you imagined this to work until I saw your PR ;) Yeah, one drawback is that scripts need to be self contained.

I'm not really fond of the current practice either. Being able to load codemods remotely is definitely a good idea. We could expand that and make it easier to load them from GitHub or gists.

If someone wants to share a more complex codemod with dependencies, they could just put it on npm.

**Comment by iamdustan** [comment]
The Browserify web service (https://wzrd.in/) could likely be used ad-hoc for the first constraint (h/t @rreverser)

Ensuring the transform is written in valid node code and not babel is the second constraint (e.g React-router codemods use es6 modules)

**Comment by fkling** [comment]
> Ensuring the transform is written in valid node code and not babel is the second constraint

jscodeshift passes transforms through Babel by default. But I guess that won't work with the browserify web service then.

**Comment by iamdustan** [comment]
What areas would you like me to explore and verify before moving forward with #95?

**Comment by fkling** [comment]
I'm fine with it as it is (if the test passes). We can always extend this when there is demand.

**Comment by iamdustan** [comment]
A test broke when remerging with master. Hope to get that fixed today.

**Comment by iamdustan** [comment]
Found the reason. https://github.com/facebook/jscodeshift/pull/95 was changed from `2` to `0` in the diff.

**Comment by cpojer** [comment]
NICE!

**Comment by iamdustan** [comment]
Who wants to add friendly URLs and the ability to request just the transform to astexplorer? 😀

**Comment by fkling** [comment]
astexplorer support is going to be more tricky, since the data has to be loaded from Parse somehow. But Parse is shutting down and we don't know yet where to move it to.

If we would run a VPS, we can have the server expose an API to load astexplorer transform data.

**Comment by RReverser** [comment]
@fkling I just thought about that once again - why don't we move to Gists instead as some popular JS playgrounds do? That way, user could load, save and share actual gists across the playgrounds and we wouldn't need to care about the storage at all.

**Comment by fkling** [comment]
@RReverser: I'd like that, I just haven't used gists programmatically yet.

**Comment by RReverser** [comment]
@fkling My only concern is that all the old URLs will still break. Not sure how to deal with them in that case.
